# Generated by Django 6.0.3 on 2026-04-02 18:32

import corpoch.chdedi.types
import django.core.serializers.json
import django.db.models.deletion
import django_pydantic_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corpoch', '0017_alter_bracketrules_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHDediServer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.PositiveIntegerField(blank=True, null=True, verbose_name='Server PID')),
                ('path', models.CharField(default='~/CHDediServer', max_length=40, verbose_name='Server Path')),
                ('config', models.CharField(choices=[('disabled', 'Disabled'), ('open', 'Open'), ('tournament', 'Tournament')], default=('disabled', 'Disabled'), max_length=16, verbose_name='Config Option')),
                ('server_settings', django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, schema=corpoch.chdedi.types.CHServerSpecificSettings, verbose_name='Configuration')),
            ],
            options={
                'verbose_name': 'Servers',
                'verbose_name_plural': 'Servers',
            },
        ),
        migrations.CreateModel(
            name='OpenConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, schema=corpoch.chdedi.types.CHServerSettings, verbose_name='Open Server Config')),
            ],
            options={
                'verbose_name': 'Server Open Settings',
                'verbose_name_plural': 'Server Open Settings',
            },
        ),
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.PositiveIntegerField(blank=True, null=True, verbose_name='Monitor PID')),
                ('redis', django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, schema=corpoch.chdedi.types.CHRedisSettings, verbose_name='Redis Config')),
                ('to_restart', models.ManyToManyField(blank=True, related_name='to_restart', to='chdedi.chdediserver', verbose_name='Servers to Restart')),
                ('to_stop', models.ManyToManyField(blank=True, related_name='to_stop', to='chdedi.chdediserver', verbose_name='Servers to Stop')),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.CreateModel(
            name='TournamentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, schema=corpoch.chdedi.types.CHServerSettings, verbose_name='Dedicated Server Config')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpoch.tournament', verbose_name='Settings for Tournament')),
            ],
            options={
                'verbose_name': 'Server Tournament Settings',
                'verbose_name_plural': 'Server Tournament Settings',
            },
        ),
        migrations.AddField(
            model_name='chdediserver',
            name='tournament_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chdedi.tournamentconfig', verbose_name='Tournament Configuration'),
        ),
    ]
