# Generated by Django 6.0.3 on 2026-04-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chdedi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chdediserver',
            options={'ordering': ['-id'], 'verbose_name': 'Servers', 'verbose_name_plural': 'Servers'},
        ),
    ]
