import discord

from discord.ext import commands

from corpoch.models import Chart
from corpoch.chdedi.models import GlobalConfig
from corpoch.dbot.models import CHEmoji
from corpoch.dbot.view.helpers import get_chart_emoji
from corpoch.dbot.view.path import PathView
from corpoch.providers import CHOpt, EncoreClient, CHStegTool, Hydra

class Path():
	def __init__(self, bot, ctx):
		self.bot = bot
		self.ctx = ctx
		self.user = ctx.user
		self.encore = EncoreClient(exact=False)
		self.chopt = CHOpt()
		self.hydra = Hydra()
		#self.tournament = None #Here as a kindness - presence of these attrs flags touney search enabled
		#self.bracket = None
		self.charts = []
		self.chart_paths = []

	async def show(self):
		view = PathView(self)
		await view.init()
		await self.ctx.interaction.edit_original_response(embeds=[self.genChartEmbed()], content=None, view=view)

	async def hide(self):
		await self.ctx.interaction.delete_original_response()

	async def showResult(self, interaction):
		if len(self.chart_paths) > 1:
			respond = await self.ctx.channel.create_thread(name="CH Path Results Thread", message=interaction)
		else:
			respond = interaction.followup

		chopts = self.chopt.opts
		hyopts = self.hydra.opts
		for chart in self.chart_paths:
			self.chart = chart
			self.emoji = await get_chart_emoji(self.bot, self.chart)
			self.chopt = CHOpt()
			self.chopt.opts = chopts

			if isinstance(chart, Chart):
				self.chopt.opts.instrument = self.chart.instrument
				self.chopt.opts.speed = self.chart.speed

			if self.chopt.opts.instrument[0] == 'drums':
				self.hydra = Hydra()
				self.hydra.opts = hyopts
				self.hydra.gen_path(self.chart)
				if not self.hydra.output:
					await interaction.followup.send("Path generation died on Hydra call.")
					await self.hide()
					return
			else:
				self.chopt.gen_path(self.chart)
				try:
					self.chopt.save_for_upload()
				except:
					pass
				if not self.chopt.url:
					await interaction.followup.send("Path generation died on CHOpt call.")
					await self.hide()
					return

			if self.chopt.opts.instrument[0] == "drums":
				await respond.send(embed=self.genHydraResultEmbed())
			else:
				await respond.send(embed=self.genCHOptResultEmbed())

		if isinstance(respond, discord.Thread):
			await respond.archive()
		await self.hide()

	async def doSearch(self, inQuery):
		self.searchData = self.chUtils.encoreSearch(inQuery)
		self.numCharts = len(self.searchData)
		self.selection = 1 if self.numCharts == 1 else -1

	def genInstructionEmbed(self) -> discord.Embed:
		embed = discord.Embed(colour=0x3FFF33)
		embed.title = "Instructions"
		embed.add_field(name="Steps", value="Use the search button to search for a chart on Encore\nUse the tournament search button to seach through tournament setlists", inline=False)
		return embed

	def genChartEmbed(self) -> discord.Embed:
		embed = discord.Embed(colour=0x3FFF33)
		embed.title = "CH Path Generator"
		chartListing = ""
		if self.charts:
			embed.add_field(name="Directions", value="Charts shown in dropdown below.\nSelect the one you want to generate a path for.\nSet options, then submit!", inline=False) 
		else:
			embed.add_field(name="Directions", value="No results found for search.\nTry searching again with different options.", inline=False) 

		if len(self.chart_paths) > 0:
			self.addEmbedToolField(embed)

		return embed

	def genEmbedBase(self) -> discord.Embed:
		embed = discord.Embed(colour=0x00F2FF)
		embed.set_author(name=f"Generated by:{self.ctx.user.display_name}", icon_url=self.ctx.user.display_avatar.url)
		embed.title = "/ch path run result"
		return embed

	def addEmbedToolField(self, embed: discord.Embed):
		if self.chopt.opts.instrument[0] == 'drums':
			embed.add_field(name="Hydra Options Used", value=f"Kick/Bass 2x: {self.hydra.opts.bass2x}\nPro Drums: {self.hydra.opts.pro}\nDepth Mode: {self.hydra.opts.depth_mode}\nDepth Value: {self.hydra.opts.depth}", inline=False)
		else:
			outStr = f"Squeeze: {self.chopt.opts.squeeze}%\nEarly Whammy: {self.chopt.opts.whammy}%\nLazy Whammy: {self.chopt.opts.lazy}ms\nWhammy Delay: {self.chopt.opts.delay}ms"
			if not isinstance(self.charts[0], Chart):
				outStr += f"\nSong Speed: {self.chopt.opts.speed}%"
			embed.add_field(name="CHOpt Options Used", value=outStr, inline=False)

	def formatChart(self) -> str:
		if isinstance(self.chart, Chart):
			return f"{self.emoji.mention} {self.chart.tournament_name}\n\nArtist: {self.chart.artist}\nAlbum: {self.chart.album}\nCharter: {self.chart.charter}\nInstrument: {self.chart.instrument}"
		else:
			return f"{self.emoji.mention} {self.chart.name}\n\nArtist: {self.chart.artist}\nAlbum: {self.chart.album}\nCharter: {self.chart.charter}\nInstrument {self.chopt.opts.instrument}"

	def genHydraResultEmbed(self) -> discord.Embed:
		embed = self.genEmbedBase()
		embed.add_field(name="Hydra Path For", value=self.formatChart(), inline=False)
		pathStr = ""
		for p in self.hydra.output:
			pathStr += f"{p}\n"
		embed.add_field(name="Path", value=pathStr, inline=False)
		self.addEmbedToolField(embed)
		return embed

	def genCHOptResultEmbed(self) -> discord.Embed:
		embed = self.genEmbedBase()
		embed.add_field(name="CHOpt Path For", value=self.formatChart(), inline=False)
		self.addEmbedToolField(embed)
		embed.add_field(name="Image Link", value=f"[Link to Image]({self.chopt.url})", inline=False)
		return embed

class CHCmds(commands.Cog):
	def __init__(self, bot):
		self.bot = bot

	ch = discord.SlashCommandGroup('ch','CloneHero tools')

	@ch.command(name='path', description='Generate a path for a given chart on Chorus', integration_types={discord.IntegrationType.guild_install, discord.IntegrationType.user_install})
	async def path(self, ctx):
		path = Path(self.bot, ctx)
		await ctx.respond(content="Setting up", ephemeral=True)
		await path.show()

	@ch.command(name='servers', description="List of CH Server's Corpo is currently running", integration_types={discord.IntegrationType.guild_install, discord.IntegrationType.user_install})
	async def servers(self, ctx, ephemeral: bool):
		embed = discord.Embed(colour=0x00F2FF)
		embed.title = "Corpo Clone Hero Dedicated Servers"
		outStr = "settings.ini file in `C:\\Users\\YOURUSERNAME\\Documents\\Clone Hero` find the [Server] section and copy+paste the server list below it. For Linux the file is `~/.clonehero/settings.ini`\n\nRestart your game and the servers should be available!"
		embed.add_field(name="How to add", value=outStr, inline=False)
		embed.add_field(name="Corpo Server List", value=f"```{GlobalConfig.objects.get().server_list}```", inline=False)
		await ctx.respond(embed=embed, ephemeral=ephemeral)

	@discord.message_command(name='CH Sten',description='Reads CH Sten data from a screenshot posted to a message', integration_types={discord.IntegrationType.guild_install, discord.IntegrationType.user_install})
	async def getScreenSten(self, ctx: discord.ApplicationContext, msg: discord.Message):
		resp = await ctx.defer(invisible=True)
		if len(msg.attachments) < 1:
			await ctx.respond("No screenshot attached to this post!", delete_after=10)
		elif len(msg.attachments) >= 1:
			#Only gets first screenshot if multiple are attached
			submission = msg.attachments[0]

		steg = CHStegTool()
		stegData = await steg.getStegInfo(submission)

		if stegData == None:
			await ctx.respond("Submitted screenshot is not a valid in-game Clone Hero screenshot", delete_after=10)
			return

		embed = steg.buildStatsEmbed("Screenshot Results")
		if len(msg.attachments) > 1:
			await ctx.respond("Only getting first screenshot data from this message", embed=embed)
		else:
			await ctx.respond(embed=embed)

def setup(bot):
	bot.add_cog(CHCmds(bot))
