# Generated by Django 5.2.11 on 2026-02-22 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corpoch', '0003_chicon_chart_difficulty_chart_instrument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHEmoji',
            fields=[
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='AppEmoji ID')),
                ('icon', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='discord', to='corpoch.chicon', verbose_name='Emote ID')),
            ],
            options={
                'verbose_name': 'Chart Icon',
                'verbose_name_plural': 'Chart Icons',
            },
        ),
    ]
