# Generated by Django 6.0.3 on 2026-04-09 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0020_matchban_player_fk_alter_bracket_id_and_more'),
        ('dbot', '0002_guilds_channels_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Is deleted/not visible by bot.'),
        ),
        migrations.AlterField(
            model_name='channels',
            name='guild',
            field=models.ForeignKey(help_text='Guild this channel is in.', on_delete=django.db.models.deletion.CASCADE, to='dbot.guilds'),
        ),
        migrations.AlterField(
            model_name='channels',
            name='id',
            field=models.BigIntegerField(help_text='Discord snowflake ID of a channel.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='channels',
            name='name',
            field=models.CharField(blank=True, help_text='Name of a discord channel.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemoji',
            name='icon',
            field=models.ForeignKey(default=-1, help_text='Associated CHIcon.', on_delete=django.db.models.deletion.CASCADE, related_name='discord', to='corpoch.chicon', verbose_name='Emote ID'),
        ),
        migrations.AlterField(
            model_name='chemoji',
            name='id',
            field=models.BigIntegerField(db_index=True, help_text='Discord snowflake ID of the AppEmoji.', primary_key=True, serialize=False, verbose_name='AppEmoji ID'),
        ),
        migrations.AlterField(
            model_name='guilds',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Is deleted/not visible by bot.'),
        ),
        migrations.AlterField(
            model_name='guilds',
            name='icon',
            field=models.CharField(blank=True, help_text='The avatar for a Guild.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guilds',
            name='id',
            field=models.BigIntegerField(help_text='Discord snowflake ID for a Guild.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guilds',
            name='name',
            field=models.CharField(blank=True, help_text='Name of a Discord Guild.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Is deleted/not visible by bot.'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='guild',
            field=models.ForeignKey(help_text='Guild this channel is in.', on_delete=django.db.models.deletion.CASCADE, to='dbot.guilds'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='id',
            field=models.BigIntegerField(help_text='Discord snowflake ID of a role.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(blank=True, help_text='Name of a discord role.', max_length=100, null=True),
        ),
    ]
