# Generated by Django 6.0.3 on 2026-04-28 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbot', '0003_alter_channels_deleted_alter_channels_guild_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guilds',
            name='admin_role',
            field=models.ForeignKey(blank=True, help_text='Discord Role for staff/admins.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_admin', to='dbot.roles', verbose_name='Discord Staff Role'),
        ),
        migrations.AddField(
            model_name='guilds',
            name='admins',
            field=models.ManyToManyField(blank=True, help_text='Admin users for this guild.', related_name='guilds_admin', to=settings.AUTH_USER_MODEL, verbose_name='Tournament Guild Admins'),
        ),
        migrations.AddField(
            model_name='guilds',
            name='ref_role',
            field=models.ForeignKey(blank=True, help_text="Discord Role for referee's to start matches.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_ref', to='dbot.roles', verbose_name='Discord Ref Role'),
        ),
        migrations.AddField(
            model_name='guilds',
            name='referees',
            field=models.ManyToManyField(blank=True, help_text='Referee users for this guild', related_name='guilds_referee', to=settings.AUTH_USER_MODEL, verbose_name='Tournament Guild Referee'),
        ),
    ]
