# Generated by Django 6.0.3 on 2026-05-02 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0023_alter_tournamentconfig_version'),
        ('dbot', '0004_guilds_admin_role_guilds_admins_guilds_ref_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemoji',
            name='name',
            field=models.CharField(blank=True, help_text='Name for emoji (optional)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='chemoji',
            name='icon',
            field=models.ForeignKey(blank=True, default=-1, help_text='Associated CHIcon.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discord', to='corpoch.chicon', verbose_name='Emote ID'),
        ),
    ]
