# Generated by Django 6.0.1 on 2026-02-01 20:14

import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSheetAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guild', models.BigIntegerField(db_index=True, verbose_name='Discord Server ID')),
                ('name', models.CharField(default='New Tournament', max_length=128, verbose_name='Name')),
                ('short_name', models.CharField(default='NT1', max_length=16, verbose_name='Short Name')),
                ('active', models.BooleanField(default=False, verbose_name='In-Progress')),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
            },
        ),
        migrations.CreateModel(
            name='TournamentBracket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_players', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)], verbose_name='Players')),
                ('num_rounds', models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(25)], verbose_name='Best Of')),
                ('num_bans', models.IntegerField(default=1, verbose_name='Num Bans')),
                ('allow_defer', models.BooleanField(default=True, verbose_name='Allow Ban Deferral')),
                ('defer_swap', models.BooleanField(default=False, verbose_name='Using Defer Alters First Pick')),
                ('score_log', models.BigIntegerField(default=-1, verbose_name='Score Log Channel Discord ID')),
                ('name', models.CharField(default='New Bracket', max_length=128, verbose_name='Bracket Name')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='corpoch.tournament', verbose_name='Tournament')),
            ],
            options={
                'verbose_name': 'Tournament Bracket',
                'verbose_name_plural': 'Tournament Brackets',
            },
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Chart Name')),
                ('md5', models.CharField(blank=True, max_length=32, verbose_name='MD5 Hash')),
                ('blake3', models.CharField(blank=True, max_length=32, verbose_name='Blake3 Hash')),
                ('charter', models.CharField(blank=True, max_length=32, verbose_name='Charter')),
                ('modifiers', multiselectfield.db.fields.MultiSelectField(choices=[('NM', 'NoModifiers'), ('DN', 'Double Notes'), ('DS', 'Dropless Sustains'), ('AS', 'All Strums'), ('NS', 'Note Shuffle'), ('BM', 'Brutal Mode')], default=['NM'], max_length=17, verbose_name='Modifiers')),
                ('speed', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1000)], verbose_name='Speed')),
                ('category', models.CharField(default='Hybrid', max_length=16, verbose_name='Chart Category')),
                ('album', models.CharField(blank=True, max_length=256, verbose_name='Album')),
                ('artist', models.CharField(blank=True, max_length=256, verbose_name='Artist')),
                ('url', models.URLField(blank=True, verbose_name='Chart URL')),
                ('brackets', models.ManyToManyField(blank=True, related_name='setlist', to='corpoch.tournamentbracket', verbose_name='Bracket Setlist')),
            ],
            options={
                'verbose_name': 'Chart',
                'verbose_name_plural': 'Charts',
            },
        ),
        migrations.CreateModel(
            name='BracketGroup',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='A', max_length=8, verbose_name='Group Name')),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='corpoch.tournamentbracket', verbose_name='Bracket Groups')),
            ],
            options={
                'verbose_name': 'Bracket Group',
                'verbose_name_plural': 'Bracket Groups',
            },
        ),
        migrations.CreateModel(
            name='TournamentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.CharField(default='Some rules go here', max_length=1024, verbose_name='Tournament Rules')),
                ('enable_gsheets', models.BooleanField(default=True, verbose_name='Gsheets Integration')),
                ('ref_role', models.BigIntegerField(blank=True, null=True, verbose_name='Discord Ref Role ID')),
                ('proof_channel', models.BigIntegerField(blank=True, null=True, verbose_name='Discord Proof Channel ID')),
                ('version', models.CharField(choices=[('v1.0.0.4080-final', 'v1.0.0.4080-final')], default=['v1.0.0.4080-final'], max_length=32, verbose_name='Clone Hero Version')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='corpoch.tournament', verbose_name='Tournament Configuration')),
            ],
            options={
                'verbose_name': 'Tournament Config',
                'verbose_name_plural': 'Tournament Configurations',
            },
        ),
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.BigIntegerField(db_index=True, verbose_name='Player Discord ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Player Active')),
                ('ch_name', models.CharField(default='New Player', max_length=128, verbose_name='Clone Hero Name')),
                ('config', models.JSONField(default=dict, verbose_name='Player Configuration')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='corpoch.tournament', verbose_name='Tournament')),
            ],
            options={
                'verbose_name': 'Tournament Player',
                'verbose_name_plural': 'Tournament Players',
            },
        ),
        migrations.CreateModel(
            name='TournamentMatchOngoing',
            fields=[
                ('id', models.CharField(default=uuid.uuid1, max_length=40, primary_key=True, serialize=False, verbose_name='Match ID')),
                ('processed', models.BooleanField(default=False, verbose_name='Match Processed')),
                ('started_on', models.DateTimeField(auto_now_add=True, verbose_name='Match Start Time')),
                ('finished', models.BooleanField(default=False, verbose_name='Match in-progress')),
                ('channel', models.BigIntegerField(null=True, verbose_name='Discord channel ID for ref-tool')),
                ('message', models.BigIntegerField(null=True, verbose_name='Discord message ID for ref-tool')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_matches', to='corpoch.bracketgroup', verbose_name='Group')),
                ('player1_ban', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_player1_ban', to='corpoch.chart', verbose_name='Player 1 Ban')),
                ('player2_ban', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_player2_ban', to='corpoch.chart', verbose_name='Player 2 Ban')),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_player1', to='corpoch.tournamentplayer', verbose_name='High Seed/Player 1')),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_player2', to='corpoch.tournamentplayer', verbose_name='Low Seed/Player 2')),
            ],
            options={
                'verbose_name': 'Ongoing Tournament Match',
                'verbose_name_plural': 'Ongoing Tournament Matches',
            },
        ),
        migrations.CreateModel(
            name='TournamentMatchCompleted',
            fields=[
                ('id', models.CharField(default=uuid.uuid1, max_length=40, primary_key=True, serialize=False, verbose_name='Match ID')),
                ('processed', models.BooleanField(default=False, verbose_name='Match Processed')),
                ('started_on', models.DateTimeField(auto_now_add=True, verbose_name='Match Start Time')),
                ('ended_on', models.DateTimeField(auto_now_add=True, verbose_name='Match end time')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_matches', to='corpoch.bracketgroup', verbose_name='Group')),
                ('player1_ban', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_player1_ban', to='corpoch.chart', verbose_name='Player 1 Ban')),
                ('player2_ban', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_player2_ban', to='corpoch.chart', verbose_name='Player 2 Ban')),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_lost', to='corpoch.tournamentplayer', verbose_name='Loser')),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_player1', to='corpoch.tournamentplayer', verbose_name='High Seed/Player 1')),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_player2', to='corpoch.tournamentplayer', verbose_name='Low Seed/Player 2')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_won', to='corpoch.tournamentplayer', verbose_name='Winner')),
            ],
            options={
                'verbose_name': 'Completed Tournament Match',
                'verbose_name_plural': 'Tournament Matches Completed',
            },
        ),
        migrations.CreateModel(
            name='GroupSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.PositiveIntegerField()),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seeding', to='corpoch.bracketgroup', verbose_name='Group Seeding')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_seed', to='corpoch.tournamentplayer', verbose_name='Group Seed')),
            ],
            options={
                'verbose_name': 'Seed Placement',
                'verbose_name_plural': 'Seed Placements',
                'ordering': ['seed'],
            },
        ),
        migrations.AddField(
            model_name='bracketgroup',
            name='players',
            field=models.ManyToManyField(to='corpoch.tournamentplayer', verbose_name='Players'),
        ),
        migrations.CreateModel(
            name='TournamentQualifier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('single_submission', models.BooleanField(default=False, verbose_name='Single Submission')),
                ('form_link', models.URLField(null=True, verbose_name='Qualifier Form Link')),
                ('end_time', models.DateTimeField(auto_now_add=True, verbose_name='Qualifier End Time')),
                ('rules', models.CharField(default='Placeholder rules', max_length=1024, verbose_name='Qualifier Rules')),
                ('gsheet', models.URLField(null=True, verbose_name='Submissions Google Sheet')),
                ('qualifier_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoch.chart', verbose_name='Qualifier Chart')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifier', to='corpoch.tournament', verbose_name='Bracket Qualifier')),
            ],
            options={
                'verbose_name': 'Qualifier',
                'verbose_name_plural': 'Qualifiers',
            },
        ),
        migrations.CreateModel(
            name='QualifierSubmission',
            fields=[
                ('quali', models.CharField(default=uuid.uuid1, max_length=40, primary_key=True, serialize=False, verbose_name='Qualifier ID')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='Submission Time')),
                ('steg_json', models.JSONField(blank=True, default=dict, verbose_name='Steg Data')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifiers', to='corpoch.tournamentplayer', verbose_name='Submittor')),
                ('qualifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='corpoch.tournamentqualifier', verbose_name='Tournament Qualifier')),
            ],
            options={
                'verbose_name': 'Qualifier Submission',
                'verbose_name_plural': 'Qualifier Submissions',
            },
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('started_on', models.DateTimeField(auto_now_add=True, verbose_name='Started')),
                ('ended_on', models.DateTimeField(blank=True, verbose_name='Ended')),
                ('steg_data', models.JSONField(blank=True, verbose_name='Steg Data')),
                ('screenshot', models.ImageField(upload_to='tournament_screens/', verbose_name='Screenshot')),
                ('chart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds_played', to='corpoch.chart', verbose_name='Chart Played')),
                ('completed_match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_match_rounds', to='corpoch.tournamentmatchcompleted', verbose_name='Completed Match')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_rounds', to='corpoch.bracketgroup', verbose_name='Group')),
                ('ongoing_match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ongoing_match_rounds', to='corpoch.tournamentmatchongoing', verbose_name='Ongoing Match')),
                ('picked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='corpoch.tournamentplayer', verbose_name='Player That Picked')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds_won', to='corpoch.tournamentplayer', verbose_name='Winner')),
            ],
            options={
                'verbose_name': 'Group Match Round',
                'verbose_name_plural': 'Group Match Rounds',
            },
        ),
    ]
