# Generated by Django 3.2.6 on 2026-01-29 02:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BracketGroup',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='A', max_length=8, verbose_name='Group Name')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('_guild', models.BigIntegerField(db_index=True, verbose_name='Discord Server ID')),
                ('name', models.CharField(default='New Tournament', max_length=128, verbose_name='Name')),
                ('short_name', models.CharField(default='NT1', max_length=16, verbose_name='Short Name')),
                ('active', models.BooleanField(default=False, verbose_name='In-Progress')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentQualifier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('single_submission', models.BooleanField(default=False, verbose_name='Single submission')),
                ('chart_link', models.URLField(null=True, verbose_name='Qualifier Download Link')),
                ('chart_checksum', models.CharField(default='NONE', max_length=32, verbose_name='Qualifier md5sum')),
                ('form_link', models.URLField(null=True, verbose_name='Qualifier form link')),
                ('end_time', models.DateTimeField(default=datetime.datetime(2026, 1, 29, 2, 59, 4, 147205, tzinfo=utc), verbose_name='Qualifier end time')),
                ('rules', models.CharField(default='Placeholder rules', max_length=1024, verbose_name='Qualifier Rules')),
                ('gsheet', models.URLField(null=True, verbose_name='Submissions Google Sheet')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifier', to='corpoch.tournament', verbose_name='Bracket Qualifier')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('_user', models.BigIntegerField(db_index=True, verbose_name='Player Discord ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Player Active')),
                ('ch_name', models.CharField(default='New Player', max_length=128, verbose_name='Clone Hero Name')),
                ('config', models.JSONField(verbose_name='Player Configuration')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='corpoch.tournament', verbose_name='Tournament Players')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentMatchOngoing',
            fields=[
                ('id', models.CharField(default='7857bb3a-fcbe-11f0-a08e-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID')),
                ('processed', models.BooleanField(default=False, verbose_name='Match processed')),
                ('started_on', models.DateTimeField(default=datetime.datetime(2026, 1, 29, 2, 59, 4, 148814, tzinfo=utc), verbose_name='Match start time')),
                ('match_results', models.JSONField(default={}, verbose_name='Match Results')),
                ('finished', models.BooleanField(default=False, verbose_name='Match in-progress')),
                ('_channel', models.BigIntegerField(null=True, verbose_name='Discord channel ID for ref-tool')),
                ('_message', models.BigIntegerField(null=True, verbose_name='Discord message ID for ref-tool')),
                ('match_data', models.JSONField(verbose_name='Match Results')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournamentmatchongoing_matches', to='corpoch.bracketgroup', verbose_name='Group match was for')),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournamentmatchongoing_player1', to='corpoch.tournamentplayer', verbose_name='High Seed/Player 1')),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournamentmatchongoing_player2', to='corpoch.tournamentplayer', verbose_name='Low Seed/Player 2')),
            ],
            options={
                'ordering': ['started_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TournamentMatchCompleted',
            fields=[
                ('id', models.CharField(default='7857bb3a-fcbe-11f0-a08e-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID')),
                ('processed', models.BooleanField(default=False, verbose_name='Match processed')),
                ('started_on', models.DateTimeField(default=datetime.datetime(2026, 1, 29, 2, 59, 4, 148814, tzinfo=utc), verbose_name='Match start time')),
                ('match_results', models.JSONField(default={}, verbose_name='Match Results')),
                ('ended_on', models.DateTimeField(default=datetime.datetime(2026, 1, 29, 2, 59, 4, 149099, tzinfo=utc), verbose_name='Match end time')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournamentmatchcompleted_matches', to='corpoch.bracketgroup', verbose_name='Group match was for')),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournamentmatchcompleted_player1', to='corpoch.tournamentplayer', verbose_name='High Seed/Player 1')),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournamentmatchcompleted_player2', to='corpoch.tournamentplayer', verbose_name='Low Seed/Player 2')),
            ],
            options={
                'ordering': ['started_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TournamentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.CharField(default='Some rules go here', max_length=1024, verbose_name='Tournament Name')),
                ('enable_gsheets', models.BooleanField(default=True, verbose_name='Gsheets Integration Enabled')),
                ('_ref_role', models.BigIntegerField(null=True, verbose_name='Discord Ref Role ID')),
                ('_proof_channel', models.BigIntegerField(null=True, verbose_name='Discord Proof Channel ID')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='corpoch.tournament', verbose_name='Tournament Configuration')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentBracket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bans', models.IntegerField(default=1, verbose_name='Num Bans')),
                ('allow_defer', models.BooleanField(default=True, verbose_name='Allow ban deferral')),
                ('defer_swap', models.BooleanField(default=False, verbose_name='Using defer alters first pick')),
                ('_score_log', models.BigIntegerField(default=-1, verbose_name='Score Log Channel Discord ID')),
                ('name', models.CharField(default='New Bracket', max_length=128, verbose_name='Bracket Name')),
                ('setlist', models.JSONField(default=dict, verbose_name='Bracket Setlist')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='corpoch.tournament', verbose_name='Tournament bracket belongs to')),
            ],
        ),
        migrations.CreateModel(
            name='QualifierSubmission',
            fields=[
                ('quali', models.CharField(default='7857f7e4-fcbe-11f0-a08e-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Qualifier ID')),
                ('steg_json', models.JSONField(default=dict, verbose_name='Steg Data')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifiers', to='corpoch.tournamentplayer', verbose_name='Submittor')),
                ('qualifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='corpoch.tournamentqualifier', verbose_name='Tournament Qualifier')),
            ],
        ),
        migrations.AddField(
            model_name='bracketgroup',
            name='bracket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='corpoch.tournamentbracket', verbose_name='Bracket Groups'),
        ),
        migrations.AddField(
            model_name='bracketgroup',
            name='players',
            field=models.ManyToManyField(to='corpoch.TournamentPlayer', verbose_name='Players'),
        ),
    ]
