# Generated by Django 5.2.11 on 2026-02-13 23:36

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import encrypted_json_fields.fields
import multiselectfield.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BracketGroup',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='A', max_length=8, verbose_name='Group Name')),
                ('discord', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Group Role Discord ID')),
            ],
            options={
                'verbose_name': 'Bracket Group',
                'verbose_name_plural': 'Bracket Groups',
            },
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Chart Name')),
                ('artist', models.CharField(blank=True, max_length=256, verbose_name='Artist')),
                ('album', models.CharField(blank=True, max_length=256, verbose_name='Album')),
                ('charter', models.CharField(blank=True, max_length=32, verbose_name='Charter')),
                ('tiebreaker', models.BooleanField(default=False, verbose_name='Tiebreaker')),
                ('modifiers', multiselectfield.db.fields.MultiSelectField(choices=[('NM', 'NoModifiers'), ('DN', 'Double Notes'), ('DS', 'Dropless Sustains'), ('AS', 'All Strums'), ('NS', 'Note Shuffle'), ('BM', 'Brutal Mode')], default=['NM'], max_length=17, verbose_name='Modifiers')),
                ('speed', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1000)], verbose_name='Speed')),
                ('category', models.CharField(default='Hybrid', max_length=16, verbose_name='Chart Category')),
                ('md5', models.CharField(blank=True, max_length=32, verbose_name='MD5 Hash')),
                ('blake3', models.CharField(blank=True, max_length=32, verbose_name='Blake3 Hash')),
                ('url', models.URLField(blank=True, verbose_name='Chart URL')),
            ],
            options={
                'verbose_name': 'Chart',
                'verbose_name_plural': 'Charts',
            },
        ),
        migrations.CreateModel(
            name='GSheetAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', encrypted_json_fields.fields.EncryptedJSONField(blank=True, crypter=None, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('sa_name', models.CharField(max_length=96, verbose_name='API Service Account Name')),
            ],
            options={
                'verbose_name': 'Google Sheets API',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guild', models.BigIntegerField(db_index=True, verbose_name='Discord Server ID')),
                ('name', models.CharField(default='New Tournament', max_length=128, verbose_name='Name')),
                ('short_name', models.CharField(default='NT1', max_length=16, verbose_name='Short Name')),
                ('active', models.BooleanField(default=False, verbose_name='In-Progress')),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
            },
        ),
        migrations.CreateModel(
            name='GroupSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.PositiveIntegerField()),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seeding', to='corpoch.bracketgroup', verbose_name='Group Seeding')),
            ],
            options={
                'verbose_name': 'Seed Placement',
                'verbose_name_plural': 'Seed Placements',
                'ordering': ['seed'],
            },
        ),
        migrations.CreateModel(
            name='TournamentBracket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_players', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)], verbose_name='Players')),
                ('num_rounds', models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(25)], verbose_name='Best Of')),
                ('num_bans', models.IntegerField(default=1, verbose_name='Num Bans')),
                ('allow_defer', models.BooleanField(default=True, verbose_name='Allow Ban Deferral')),
                ('defer_swap', models.BooleanField(default=False, verbose_name='Using Defer Alters First Pick')),
                ('last_loser_picks', models.BooleanField(default=True, verbose_name='Loser Last Round Picks')),
                ('tiebeaker_csc', models.BooleanField(default=False, verbose_name='Tibeaker CSC Rules')),
                ('score_log', models.BigIntegerField(default=-1, verbose_name='Score Log Channel Discord ID')),
                ('name', models.CharField(default='New Bracket', max_length=128, verbose_name='Bracket Name')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='corpoch.tournament', verbose_name='Tournament')),
            ],
            options={
                'verbose_name': 'Bracket',
                'verbose_name_plural': 'Brackets',
            },
        ),
        migrations.CreateModel(
            name='Qualifier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('limit_submissions', models.BooleanField(default=False, verbose_name='Limit Submissions to # Required')),
                ('required_submissions', models.PositiveIntegerField(default=1, verbose_name='Required Submissions')),
                ('form_link', models.URLField(blank=True, null=True, verbose_name='Google Form Link')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='End Time')),
                ('rules', models.TextField(default='Placeholder rules', max_length=1024, verbose_name='Rules')),
                ('channel', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Submission Discord Channel ID')),
                ('gsheet', models.URLField(blank=True, null=True, verbose_name='Submissions Google Sheet')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoch.chart', verbose_name='Qualifier Chart')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifier', to='corpoch.tournament', verbose_name='Tournament')),
                ('bracket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualifier', to='corpoch.tournamentbracket', verbose_name='Bracket')),
            ],
            options={
                'verbose_name': 'Qualifier',
                'verbose_name_plural': 'Qualifiers',
            },
        ),
        migrations.AddField(
            model_name='chart',
            name='brackets',
            field=models.ManyToManyField(blank=True, related_name='setlist', to='corpoch.tournamentbracket', verbose_name='Bracket Setlist'),
        ),
        migrations.AddField(
            model_name='bracketgroup',
            name='bracket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='corpoch.tournamentbracket', verbose_name='Bracket Groups'),
        ),
        migrations.CreateModel(
            name='TournamentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.TextField(default='Some rules go here', max_length=1024, verbose_name='Rules')),
                ('ref_role', models.BigIntegerField(blank=True, null=True, verbose_name='Discord Ref Role ID')),
                ('proof_channel', models.BigIntegerField(blank=True, null=True, verbose_name='Discord Proof Channel ID')),
                ('enable_gsheets', models.BooleanField(default=True, verbose_name='Gsheets Integration')),
                ('gsheet', models.URLField(blank=True, null=True, verbose_name='Match Reporting Google Sheet')),
                ('version', models.CharField(choices=[('v1.0.0.4080-final', 'v1.0.0.4080-final')], default=['v1.0.0.4080-final'], max_length=32, verbose_name='Clone Hero Version')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='corpoch.tournament', verbose_name='Tournament Configuration')),
            ],
            options={
                'verbose_name': 'Config',
                'verbose_name_plural': 'Configurations',
            },
        ),
        migrations.CreateModel(
            name='TournamentMatchCompleted',
            fields=[
                ('id', models.CharField(default=uuid.uuid1, max_length=40, primary_key=True, serialize=False, verbose_name='Match ID')),
                ('processed', models.BooleanField(default=False, verbose_name='Match Processed')),
                ('started_on', models.DateTimeField(auto_now_add=True, verbose_name='Match Start Time')),
                ('ended_on', models.DateTimeField(auto_now_add=True, verbose_name='Match end time')),
                ('submitted', models.BooleanField(default=False, verbose_name='Uploaded to GSheet')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_matches', to='corpoch.bracketgroup', verbose_name='Group')),
                ('match_players', models.ManyToManyField(blank=True, related_name='%(class)s_players', to='corpoch.groupseed', verbose_name='Players')),
            ],
            options={
                'verbose_name': 'Completed Match',
                'verbose_name_plural': 'Matches Completed',
            },
        ),
        migrations.CreateModel(
            name='TournamentMatchOngoing',
            fields=[
                ('id', models.CharField(default=uuid.uuid1, max_length=40, primary_key=True, serialize=False, verbose_name='Match ID')),
                ('processed', models.BooleanField(default=False, verbose_name='Match Processed')),
                ('started_on', models.DateTimeField(auto_now_add=True, verbose_name='Match Start Time')),
                ('finished', models.BooleanField(default=False, verbose_name='Finished')),
                ('channel', models.BigIntegerField(blank=True, null=True, verbose_name='Ref-Tool Discord Channel ID')),
                ('message', models.BigIntegerField(blank=True, null=True, verbose_name='Ref-Tool Discord Message ID')),
                ('ref', models.BigIntegerField(blank=True, null=True, verbose_name='Discord Ref ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_matches', to='corpoch.bracketgroup', verbose_name='Group')),
                ('match_players', models.ManyToManyField(blank=True, related_name='%(class)s_players', to='corpoch.groupseed', verbose_name='Players')),
            ],
            options={
                'verbose_name': 'Ongoing Match',
                'verbose_name_plural': 'Ongoing Matches',
            },
        ),
        migrations.CreateModel(
            name='MatchBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField()),
                ('chart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans', to='corpoch.chart', verbose_name='Chart Banned')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_bans', to='corpoch.groupseed', verbose_name='Player')),
                ('completed_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_bans', to='corpoch.tournamentmatchcompleted', verbose_name='Completed Match ID')),
                ('ongoing_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_bans', to='corpoch.tournamentmatchongoing', verbose_name='Ongoing Match ID')),
            ],
            options={
                'verbose_name': 'Match Ban',
                'verbose_name_plural': 'Match Bans',
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.BigIntegerField(db_index=True, verbose_name='Player Discord ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Discord Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Player Active')),
                ('ch_name', models.CharField(default='New Player', max_length=128, verbose_name='Clone Hero Name')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Player Configuration')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='corpoch.tournament', verbose_name='Tournament')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.AddField(
            model_name='tournamentmatchcompleted',
            name='loser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_lost', to='corpoch.tournamentplayer', verbose_name='Loser'),
        ),
        migrations.AddField(
            model_name='tournamentmatchcompleted',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_won', to='corpoch.tournamentplayer', verbose_name='Winner'),
        ),
        migrations.CreateModel(
            name='QualifierSubmission',
            fields=[
                ('id', models.CharField(default=uuid.uuid1, max_length=40, primary_key=True, serialize=False, verbose_name='Qualifier ID')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='Submission Time')),
                ('screenshot', models.ImageField(null=True, upload_to='qualifiers/', verbose_name='Screenshot')),
                ('steg', models.JSONField(blank=True, default=dict, verbose_name='Steg Data')),
                ('submitted', models.BooleanField(default=False, verbose_name='Uploaded to GSheet')),
                ('qualifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='corpoch.qualifier', verbose_name='Tournament Qualifier')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifiers', to='corpoch.tournamentplayer', verbose_name='Submittor')),
            ],
            options={
                'verbose_name': 'Qualifier Submission',
                'verbose_name_plural': 'Qualifier Submissions',
            },
        ),
        migrations.CreateModel(
            name='MatchRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField()),
                ('steg', models.JSONField(blank=True, null=True, verbose_name='Steg Data')),
                ('screenshot', models.ImageField(null=True, upload_to='rounds/', verbose_name='Screenshot')),
                ('chart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds_played', to='corpoch.chart', verbose_name='Chart Played')),
                ('completed_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completeds_rounds', to='corpoch.tournamentmatchcompleted', verbose_name='Completed Match ID')),
                ('ongoing_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ongoing_rounds', to='corpoch.tournamentmatchongoing', verbose_name='Ongoing Match ID')),
                ('loser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds_lost', to='corpoch.tournamentplayer', verbose_name='Loser')),
                ('picked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='corpoch.tournamentplayer', verbose_name='Picked')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds_won', to='corpoch.tournamentplayer', verbose_name='Winner')),
            ],
            options={
                'verbose_name': 'Group Match Round',
                'verbose_name_plural': 'Group Match Rounds',
                'ordering': ['num'],
            },
        ),
        migrations.AddField(
            model_name='groupseed',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_seeding', to='corpoch.tournamentplayer', verbose_name='Group Seed'),
        ),
    ]
