# Generated by Django 5.2.11 on 2026-02-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bracketgroup',
            name='discord',
        ),
        migrations.RemoveField(
            model_name='qualifier',
            name='chart',
        ),
        migrations.AddField(
            model_name='bracketgroup',
            name='role',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Discord Group Role ID'),
        ),
        migrations.AddField(
            model_name='qualifier',
            name='charts',
            field=models.ManyToManyField(related_name='charts', to='corpoch.chart', verbose_name='Qualifier Chart(s)'),
        ),
    ]
