# Generated by Django 6.0.1 on 2026-02-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentbracket',
            options={'verbose_name': 'Bracket', 'verbose_name_plural': 'Brackets'},
        ),
        migrations.AlterModelOptions(
            name='tournamentconfig',
            options={'verbose_name': 'Config', 'verbose_name_plural': 'Configurations'},
        ),
        migrations.AlterModelOptions(
            name='tournamentmatchcompleted',
            options={'verbose_name': 'Completed Match', 'verbose_name_plural': 'Matches Completed'},
        ),
        migrations.AlterModelOptions(
            name='tournamentmatchongoing',
            options={'verbose_name': 'Ongoing Match', 'verbose_name_plural': 'Ongoing Matches'},
        ),
        migrations.AlterModelOptions(
            name='tournamentplayer',
            options={'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.RemoveField(
            model_name='tournamentmatchcompleted',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='tournamentmatchcompleted',
            name='player1_ban',
        ),
        migrations.RemoveField(
            model_name='tournamentmatchcompleted',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='tournamentmatchcompleted',
            name='player2_ban',
        ),
        migrations.RemoveField(
            model_name='tournamentmatchongoing',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='tournamentmatchongoing',
            name='player1_ban',
        ),
        migrations.RemoveField(
            model_name='tournamentmatchongoing',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='tournamentmatchongoing',
            name='player2_ban',
        ),
        migrations.AddField(
            model_name='tournamentmatchcompleted',
            name='match_players',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_players', to='corpoch.tournamentplayer', verbose_name='Players'),
        ),
        migrations.AddField(
            model_name='tournamentmatchongoing',
            name='match_players',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_players', to='corpoch.tournamentplayer', verbose_name='Players'),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='rules',
            field=models.CharField(default='Some rules go here', max_length=1024, verbose_name='Rules'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='channel',
            field=models.BigIntegerField(null=True, verbose_name='Ref-Tool Discord Channel ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Finished'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='message',
            field=models.BigIntegerField(null=True, verbose_name='Ref-Tool Discord Message ID'),
        ),
    ]
