# Generated by Django 3.2.6 on 2026-01-29 02:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='quali',
            field=models.CharField(default='7b175f60-fcbe-11f0-a8cc-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Qualifier ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='ended_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 2, 59, 8, 758900, tzinfo=utc), verbose_name='Match end time'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='id',
            field=models.CharField(default='7b1720f4-fcbe-11f0-a8cc-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='started_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 2, 59, 8, 758596, tzinfo=utc), verbose_name='Match start time'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='id',
            field=models.CharField(default='7b1720f4-fcbe-11f0-a8cc-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='started_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 2, 59, 8, 758596, tzinfo=utc), verbose_name='Match start time'),
        ),
        migrations.AlterField(
            model_name='tournamentqualifier',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 2, 59, 8, 757013, tzinfo=utc), verbose_name='Qualifier end time'),
        ),
    ]
