# Generated by Django 5.2.11 on 2026-02-22 02:18

import django.db.models.deletion
import encrypted_fields.fields
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0002_remove_bracketgroup_discord_remove_qualifier_chart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHIcon',
            fields=[
                ('name', models.CharField(default='newicon', max_length=32, primary_key=True, serialize=False, verbose_name='Name')),
                ('img', models.ImageField(blank=True, null=True, upload_to='chicons/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Chart Icon',
                'verbose_name_plural': 'Chart Icons',
            },
        ),
        migrations.AddField(
            model_name='chart',
            name='difficulty',
            field=models.CharField(choices=[('expert', 'Expert'), ('hard', 'Hard'), ('medium', 'Medium'), ('easy', 'Easy')], default='expert', max_length=16, null=True, verbose_name='Difficulty'),
        ),
        migrations.AddField(
            model_name='chart',
            name='instrument',
            field=models.CharField(choices=[('guitar', 'Guitar'), ('coop', 'Guitar Coop'), ('bass', 'Bass'), ('rhythm', 'Rhythm'), ('keys', 'Keys'), ('drums', 'Drums'), ('ghl', 'GHL Guitar'), ('ghlbass', 'GHL Bass'), ('ghlrythm', 'GHL Rhythm'), ('ghlcoop', 'GHL Guitar Coop')], default='guitar', max_length=32, verbose_name='Instrument'),
        ),
        migrations.AlterField(
            model_name='bracketgroup',
            name='role',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Discord Role ID'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='category',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('fret', 'Fret'), ('strum', 'Strum'), ('sprint', 'Sprint'), ('marathon', 'Marathon'), ('none', 'None')], default='hybrid', max_length=16, verbose_name='Chart Category'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='modifiers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NM', 'NoModifiers'), ('DN', 'Double Notes'), ('DS', 'Dropless Sustains'), ('AS', 'All Strums'), ('NS', 'Note Shuffle'), ('BM', 'Brutal Mode')], default='NM', max_length=17, verbose_name='Modifiers'),
        ),
        migrations.AlterField(
            model_name='gsheetapi',
            name='api_key',
            field=encrypted_fields.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='version',
            field=models.CharField(choices=[('v1.0.0.4080-final', 'v1.0.0.4080-final')], default='v1.0.0.4080-final', max_length=32, verbose_name='Clone Hero Version'),
        ),
        migrations.AddField(
            model_name='chart',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charts', to='corpoch.chicon', verbose_name='CH Icon'),
        ),
    ]
