# Generated by Django 3.2.6 on 2026-01-29 04:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0002_auto_20260129_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='_guild',
            new_name='guild',
        ),
        migrations.RenameField(
            model_name='tournamentbracket',
            old_name='_score_log',
            new_name='score_log',
        ),
        migrations.RenameField(
            model_name='tournamentconfig',
            old_name='_proof_channel',
            new_name='proof_channel',
        ),
        migrations.RenameField(
            model_name='tournamentconfig',
            old_name='_ref_role',
            new_name='ref_role',
        ),
        migrations.RenameField(
            model_name='tournamentmatchongoing',
            old_name='_channel',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='tournamentmatchongoing',
            old_name='_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='tournamentplayer',
            old_name='_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='quali',
            field=models.CharField(default='1c52fb72-fcca-11f0-892b-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Qualifier ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='ended_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 4, 22, 23, 726872, tzinfo=utc), verbose_name='Match end time'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='id',
            field=models.CharField(default='1c52bfcc-fcca-11f0-892b-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='started_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 4, 22, 23, 726564, tzinfo=utc), verbose_name='Match start time'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='id',
            field=models.CharField(default='1c52bfcc-fcca-11f0-892b-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='started_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 4, 22, 23, 726564, tzinfo=utc), verbose_name='Match start time'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='config',
            field=models.JSONField(default={'config': None}, verbose_name='Player Configuration'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='corpoch.tournament', verbose_name='Tournament'),
        ),
        migrations.AlterField(
            model_name='tournamentqualifier',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 4, 22, 23, 724934, tzinfo=utc), verbose_name='Qualifier end time'),
        ),
    ]
