# Generated by Django 6.0.1 on 2026-02-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0002_alter_tournamentbracket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='tiebraker',
            field=models.BooleanField(default=False, verbose_name='Tiebreaker'),
        ),
    ]
