# Generated by Django 6.0.1 on 2026-02-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0003_chart_tiebraker'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatchcompleted',
            name='bans',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_bans', to='corpoch.chart', verbose_name='Bans'),
        ),
        migrations.AddField(
            model_name='tournamentmatchongoing',
            name='bans',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_bans', to='corpoch.chart', verbose_name='Bans'),
        ),
    ]
