# Generated by Django 5.2.11 on 2026-02-24 01:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0003_chicon_chart_difficulty_chart_instrument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BracketRules',
            fields=[
                ('bracket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ruleset', serialize=False, to='corpoch.tournamentbracket', verbose_name='Bracket Rules')),
                ('num_players', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)], verbose_name='Players')),
                ('num_bans', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Num Bans')),
                ('num_rounds', models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(25)], verbose_name='Best Of')),
                ('ban_ruleset', models.CharField(choices=[('default', 'No Defer/High Seed first'), ('deferban', 'High Seed can defer ban/picks first'), ('deferboth', 'High Seed can defers both ban/pick')], default='default', max_length=32, verbose_name='Match Bans Ruleset')),
                ('pick_ruleset', models.CharField(choices=[('loserpicks', 'High Seed 1st Pick/Loser Picks'), ('alternate', 'Alternate player picks')], default='loserpicks', max_length=32, verbose_name="'Who Picks' Ruleset")),
                ('tb_ruleset', models.CharField(choices=[('single', 'Single TB'), ('csc', 'CSC TB Rules'), ('banpick', "'NPDO' Ban/Pick"), ('refdecide', 'Ref picks from unplayed')], default='single', max_length=32, verbose_name='Tiebreaker Ruleset')),
            ],
        ),
        migrations.RemoveField(
            model_name='tournamentbracket',
            name='allow_defer',
        ),
        migrations.RemoveField(
            model_name='tournamentbracket',
            name='defer_swap',
        ),
        migrations.RemoveField(
            model_name='tournamentbracket',
            name='last_loser_picks',
        ),
        migrations.RemoveField(
            model_name='tournamentbracket',
            name='num_bans',
        ),
        migrations.RemoveField(
            model_name='tournamentbracket',
            name='num_players',
        ),
        migrations.RemoveField(
            model_name='tournamentbracket',
            name='num_rounds',
        ),
        migrations.RemoveField(
            model_name='tournamentbracket',
            name='tiebeaker_csc',
        ),
        migrations.AddField(
            model_name='tournamentbracket',
            name='revealed',
            field=models.BooleanField(default=False, verbose_name='Setlist Revealed'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='category',
            field=models.CharField(choices=[('none', 'None'), ('hybrid', 'Hybrid'), ('fret', 'Fret'), ('strum', 'Strum'), ('sprint', 'Sprint'), ('marathon', 'Marathon')], default='none', max_length=16, verbose_name='Chart Category'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='difficulty',
            field=models.CharField(choices=[('expert', 'Expert'), ('hard', 'Hard'), ('medium', 'Medium'), ('easy', 'Easy')], default='expert', max_length=16, verbose_name='Difficulty'),
        ),
    ]
