# Generated by Django 5.2.11 on 2026-02-28 15:33

import corpoch.models
import corpoch.types
import corpoch.validators
import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import django_pydantic_field.fields
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0004_bracketrules_remove_tournamentbracket_allow_defer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bracketrules',
            options={'verbose_name': 'Bracket Rules'},
        ),
        migrations.AddField(
            model_name='chart',
            name='sngfile',
            field=models.FileField(blank=True, null=True, upload_to='sngfiles/', validators=[corpoch.validators.validate_chart_file], verbose_name='SNG File'),
        ),
        migrations.AddField(
            model_name='tournamentbracket',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Bracket Active'),
        ),
        migrations.AddField(
            model_name='tournamentmatchcompleted',
            name='defer',
            field=models.BooleanField(default=False, verbose_name='Deferral Used'),
        ),
        migrations.AddField(
            model_name='tournamentmatchongoing',
            name='defer',
            field=models.BooleanField(default=False, verbose_name='Deferral Used'),
        ),
        migrations.AlterField(
            model_name='bracketrules',
            name='num_bans',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Bans Per-Player'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='modifiers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NM', 'No Modifiers'), ('AH', 'All Hopos'), ('AS', 'All Strums'), ('AT', 'All Taps'), ('AO', 'All Opens'), ('BM', 'Brutal Mode'), ('DD', 'Deadly Dynamics'), ('DN', 'Double Notes'), ('DS', 'Dropless Sustains'), ('PM', 'Precision Mode'), ('NS', 'Note Shuffle'), ('DK', 'Double Kick'), ('NK', 'No Kick')], default='NM', max_length=38, verbose_name='Modifiers'),
        ),
        migrations.AlterField(
            model_name='groupseed',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchban',
            name='completed_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_bans', to='corpoch.tournamentmatchcompleted', verbose_name='Completed Match ID'),
        ),
        migrations.AlterField(
            model_name='matchban',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchban',
            name='ongoing_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ongoing_bans', to='corpoch.tournamentmatchongoing', verbose_name='Ongoing Match ID'),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='completed_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_rounds', to='corpoch.tournamentmatchcompleted', verbose_name='Completed Match ID'),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds_lost', to='corpoch.tournamentplayer', verbose_name='Loser'),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='picked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='corpoch.tournamentplayer', verbose_name='Picked'),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=corpoch.models.steg_upload_dir, verbose_name='Screenshot'),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='steg',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, schema=corpoch.types.StegScreenshot, verbose_name='Steg Data'),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds_won', to='corpoch.tournamentplayer', verbose_name='Winner'),
        ),
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=corpoch.models.quali_upload_dir, verbose_name='Screenshot'),
        ),
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='steg',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, schema=corpoch.types.StegScreenshot, verbose_name='Steg Data'),
        ),
    ]
