# Generated by Django 6.0.1 on 2026-02-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0004_tournamentmatchcompleted_bans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='channel',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Ref-Tool Discord Channel ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='message',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Ref-Tool Discord Message ID'),
        ),
    ]
