# Generated by Django 3.2.6 on 2026-01-29 05:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0004_auto_20260129_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Some Chart', max_length=256, verbose_name='Chart Name')),
                ('checksum', models.CharField(default='NONE', max_length=32, verbose_name='Chart md5sum')),
                ('charter', models.CharField(default='Me', max_length=32, verbose_name='Charter')),
                ('modifiers', multiselectfield.db.fields.MultiSelectField(choices=[('DN', 'Double Notes'), ('DS', 'Dropless Sustains'), ('AS', 'All Strums'), ('NS', 'Note Shuffle'), ('BM', 'Brutal Mode')], max_length=14, null=True, verbose_name='Modifiers')),
                ('speed', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1000)], verbose_name='Speed')),
                ('category', models.CharField(default='Hybrid', max_length=16, verbose_name='Chart Category')),
                ('album', models.CharField(default='My album', max_length=256, verbose_name='Album')),
                ('artist', models.CharField(default='You', max_length=256, verbose_name='Artist')),
                ('url', models.URLField(null=True, verbose_name='Chart URL')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tournamentconfig',
            options={'verbose_name': 'Tournament Config', 'verbose_name_plural': 'Tournament Configurations'},
        ),
        migrations.AlterModelOptions(
            name='tournamentmatchcompleted',
            options={'verbose_name': 'Completed Tournament Match', 'verbose_name_plural': 'Tournament Matches Completed'},
        ),
        migrations.AlterModelOptions(
            name='tournamentmatchongoing',
            options={'verbose_name': 'Ongoing Tournament Match', 'verbose_name_plural': 'Tournament Matches Ongoing'},
        ),
        migrations.RemoveField(
            model_name='tournamentqualifier',
            name='chart_checksum',
        ),
        migrations.RemoveField(
            model_name='tournamentqualifier',
            name='chart_link',
        ),
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='quali',
            field=models.CharField(default='d6b0ebe6-fcd4-11f0-a7e2-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Qualifier ID'),
        ),
        migrations.AlterField(
            model_name='tournamentbracket',
            name='allow_defer',
            field=models.BooleanField(default=True, verbose_name='Allow Ban deferral'),
        ),
        migrations.AlterField(
            model_name='tournamentbracket',
            name='defer_swap',
            field=models.BooleanField(default=False, verbose_name='Using Defer Alters First Pick'),
        ),
        migrations.AlterField(
            model_name='tournamentbracket',
            name='setlist',
            field=models.JSONField(default={'somedate': None}, verbose_name='Bracket Setlist'),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='enable_gsheets',
            field=models.BooleanField(default=True, verbose_name='Gsheets Integration'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='ended_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 5, 39, 11, 365850, tzinfo=utc), verbose_name='Match end time'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournamentmatchcompleted_matches', to='corpoch.bracketgroup', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='id',
            field=models.CharField(default='d6b0ae06-fcd4-11f0-a7e2-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Match Processed'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='started_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 5, 39, 11, 365595, tzinfo=utc), verbose_name='Match Start Time'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournamentmatchongoing_matches', to='corpoch.bracketgroup', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='id',
            field=models.CharField(default='d6b0ae06-fcd4-11f0-a7e2-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Match Processed'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='started_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 5, 39, 11, 365595, tzinfo=utc), verbose_name='Match Start Time'),
        ),
        migrations.AlterField(
            model_name='tournamentqualifier',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 5, 39, 11, 364268, tzinfo=utc), verbose_name='Qualifier End Time'),
        ),
        migrations.AlterField(
            model_name='tournamentqualifier',
            name='form_link',
            field=models.URLField(null=True, verbose_name='Qualifier Form Link'),
        ),
        migrations.AlterField(
            model_name='tournamentqualifier',
            name='single_submission',
            field=models.BooleanField(default=False, verbose_name='Single Submission'),
        ),
        migrations.AddField(
            model_name='tournamentqualifier',
            name='qualifier_chart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='corpoch.chart', verbose_name='Qualifier Chart'),
            preserve_default=False,
        ),
    ]
