# Generated by Django 3.2.6 on 2026-01-29 05:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0005_auto_20260129_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='quali',
            field=models.CharField(default='e8813308-fcd4-11f0-96aa-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Qualifier ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='ended_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 5, 39, 41, 251862, tzinfo=utc), verbose_name='Match end time'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='id',
            field=models.CharField(default='e880eac4-fcd4-11f0-96aa-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='started_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 5, 39, 41, 251585, tzinfo=utc), verbose_name='Match Start Time'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='id',
            field=models.CharField(default='e880eac4-fcd4-11f0-96aa-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='started_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 5, 39, 41, 251585, tzinfo=utc), verbose_name='Match Start Time'),
        ),
        migrations.AlterField(
            model_name='tournamentqualifier',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 5, 39, 41, 250071, tzinfo=utc), verbose_name='Qualifier End Time'),
        ),
    ]
