# Generated by Django 6.0.1 on 2026-02-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0005_alter_tournamentmatchongoing_channel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentround',
            options={'ordering': ['num'], 'verbose_name': 'Group Match Round', 'verbose_name_plural': 'Group Match Rounds'},
        ),
        migrations.AddField(
            model_name='tournamentround',
            name='num',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
