# Generated by Django 5.2.11 on 2026-02-28 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0005_alter_bracketrules_options_chart_sngfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchround',
            name='loser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds_lost', to='corpoch.tournamentplayer', verbose_name='Loser'),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds_won', to='corpoch.tournamentplayer', verbose_name='Winner'),
        ),
    ]
