# Generated by Django 3.2.6 on 2026-01-29 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0006_auto_20260129_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='checksum',
            new_name='md5',
        ),
        migrations.AlterField(
            model_name='chart',
            name='modifiers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NM', 'NoModifiers'), ('DN', 'Double Notes'), ('DS', 'Dropless Sustains'), ('AS', 'All Strums'), ('NS', 'Note Shuffle'), ('BM', 'Brutal Mode')], default=['NM'], max_length=17, verbose_name=(('NM', 'NoModifiers'), ('DN', 'Double Notes'), ('DS', 'Dropless Sustains'), ('AS', 'All Strums'), ('NS', 'Note Shuffle'), ('BM', 'Brutal Mode'))),
        ),
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='quali',
            field=models.CharField(default='995c7948-fd2b-11f0-9fe5-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Qualifier ID'),
        ),
        migrations.RemoveField(
            model_name='tournamentbracket',
            name='setlist',
        ),
        migrations.AddField(
            model_name='tournamentbracket',
            name='setlist',
            field=models.ManyToManyField(to='corpoch.Chart', verbose_name='Setlist'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='ended_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 16, 0, 14, 686849, tzinfo=utc), verbose_name='Match end time'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='id',
            field=models.CharField(default='995c2a92-fd2b-11f0-9fe5-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='started_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 16, 0, 14, 686513, tzinfo=utc), verbose_name='Match Start Time'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='id',
            field=models.CharField(default='995c2a92-fd2b-11f0-9fe5-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='started_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 16, 0, 14, 686513, tzinfo=utc), verbose_name='Match Start Time'),
        ),
        migrations.AlterField(
            model_name='tournamentqualifier',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 16, 0, 14, 684797, tzinfo=utc), verbose_name='Qualifier End Time'),
        ),
    ]
