# Generated by Django 5.2.11 on 2026-03-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0006_alter_matchround_loser_alter_matchround_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='role',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Participant Role ID'),
        ),
        migrations.AddField(
            model_name='tournamentbracket',
            name='role',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Bracket Role ID'),
        ),
    ]
