# Generated by Django 6.0.1 on 2026-02-02 05:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0006_alter_tournamentround_options_tournamentround_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentround',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tournamentround',
            name='started_on',
        ),
        migrations.AddField(
            model_name='tournamentround',
            name='completed_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ongoing_rounds', to='corpoch.tournamentmatchcompleted', verbose_name='Ongoing Match ID'),
        ),
        migrations.AddField(
            model_name='tournamentround',
            name='ongoing_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ongoing_rounds', to='corpoch.tournamentmatchongoing', verbose_name='Ongoing Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='id',
            field=models.CharField(default=uuid.uuid1, max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
    ]
