# Generated by Django 5.2.11 on 2026-03-11 05:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0007_tournament_role_tournamentbracket_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bracketgroup',
            name='bracket',
        ),
        migrations.RemoveField(
            model_name='tournamentmatchongoing',
            name='group',
        ),
        migrations.RemoveField(
            model_name='tournamentbracket',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='matchban',
            name='completed_match',
        ),
        migrations.RemoveField(
            model_name='matchround',
            name='completed_match',
        ),
        migrations.RemoveField(
            model_name='tournamentmatchongoing',
            name='match_players',
        ),
        migrations.RemoveField(
            model_name='matchban',
            name='ongoing_match',
        ),
        migrations.RemoveField(
            model_name='matchround',
            name='ongoing_match',
        ),
        migrations.AlterField(
            model_name='matchround',
            name='picked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='corpoch.tournamentplayer', verbose_name='Picker'),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='New Bracket', max_length=128, verbose_name='Bracket Name')),
                ('score_log', models.BigIntegerField(blank=True, null=True, verbose_name='Score Log Channel ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Bracket Active')),
                ('revealed', models.BooleanField(default=False, verbose_name='Setlist Revealed')),
                ('role', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Bracket Role ID')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='corpoch.tournament', verbose_name='Tournament')),
            ],
            options={
                'verbose_name': 'Bracket',
            },
        ),
        migrations.AlterField(
            model_name='bracketrules',
            name='bracket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ruleset', serialize=False, to='corpoch.bracket', verbose_name='Bracket Rules'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='brackets',
            field=models.ManyToManyField(blank=True, related_name='setlist', to='corpoch.bracket', verbose_name='Bracket Setlist'),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='bracket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualifier', to='corpoch.bracket', verbose_name='Bracket'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='A', max_length=8, verbose_name='Group Name')),
                ('role', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Discord Role ID')),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='corpoch.bracket', verbose_name='Bracket')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.AlterField(
            model_name='groupseed',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seeding', to='corpoch.group', verbose_name='Group Seeding'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.CharField(default=uuid.uuid1, max_length=40, primary_key=True, serialize=False, verbose_name='Match ID')),
                ('defer', models.BooleanField(default=False, verbose_name='Deferral Used')),
                ('started_on', models.DateTimeField(auto_now_add=True, verbose_name='Match Start Time')),
                ('ended_on', models.DateTimeField(blank=True, null=True, verbose_name='Match End Time')),
                ('complete', models.BooleanField(default=False, verbose_name="Match 'Complete'")),
                ('finished', models.BooleanField(default=False, verbose_name='Finished')),
                ('submitted', models.BooleanField(default=False, verbose_name='Uploaded to GSheet')),
                ('channel', models.BigIntegerField(blank=True, null=True, verbose_name='Ref-Tool Discord Channel ID')),
                ('message', models.BigIntegerField(blank=True, null=True, verbose_name='Ref-Tool Discord Message ID')),
                ('referee', models.BigIntegerField(blank=True, null=True, verbose_name='Discord Ref ID')),
                ('exhibition', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='corpoch.group', verbose_name='Group')),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_lost', to='corpoch.tournamentplayer')),
                ('players', models.ManyToManyField(blank=True, related_name='players', to='corpoch.groupseed', verbose_name='Players')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='corpoch.tournamentplayer')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['-started_on'],
            },
        ),
        migrations.AddField(
            model_name='matchban',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_bans', to='corpoch.match', verbose_name='Match ID'),
        ),
        migrations.AddField(
            model_name='matchround',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_rounds', to='corpoch.match', verbose_name='Match ID'),
        ),
        migrations.DeleteModel(
            name='TournamentMatchCompleted',
        ),
        migrations.DeleteModel(
            name='TournamentMatchOngoing',
        ),
        migrations.DeleteModel(
            name='TournamentBracket',
        ),
        migrations.DeleteModel(
            name='BracketGroup',
        ),
    ]
