# Generated by Django 6.0.1 on 2026-02-02 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0008_alter_tournamentround_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentround',
            name='ended_on',
        ),
        migrations.RemoveField(
            model_name='tournamentround',
            name='group',
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='completed_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completeds_rounds', to='corpoch.tournamentmatchcompleted', verbose_name='Completed Match ID'),
        ),
    ]
