# Generated by Django 3.2.6 on 2026-01-29 18:21

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0008_auto_20260129_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmatchongoing',
            name='match_data',
        ),
        migrations.AddField(
            model_name='qualifiersubmission',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Submission Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournamentconfig',
            name='version',
            field=models.CharField(choices=[('v1.0.0.4080-final', 'v1.0.0.4080-final')], default=['v1.0.0.4080-final'], max_length=32, verbose_name='Clone Hero Version'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='modifiers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NM', 'NoModifiers'), ('DN', 'Double Notes'), ('DS', 'Dropless Sustains'), ('AS', 'All Strums'), ('NS', 'Note Shuffle'), ('BM', 'Brutal Mode')], default=['NM'], max_length=17, verbose_name='Modifiers'),
        ),
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='quali',
            field=models.CharField(default='4fdc9fdc-fd3f-11f0-8d2f-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Qualifier ID'),
        ),
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='steg_json',
            field=models.JSONField(default=list, verbose_name='Steg Data'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='ended_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Match end time'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='id',
            field=models.CharField(default='4fdc68d2-fd3f-11f0-8d2f-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='match_results',
            field=models.JSONField(default=list, verbose_name='Match Results'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='started_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Match Start Time'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='id',
            field=models.CharField(default='4fdc68d2-fd3f-11f0-8d2f-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='match_results',
            field=models.JSONField(default=list, verbose_name='Match Results'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='started_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Match Start Time'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='config',
            field=models.JSONField(default=list, verbose_name='Player Configuration'),
        ),
        migrations.AlterField(
            model_name='tournamentqualifier',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qualifier End Time'),
        ),
    ]
