# Generated by Django 5.2.11 on 2026-03-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0008_remove_bracketgroup_bracket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='match_players', to='corpoch.groupseed', verbose_name='Players'),
        ),
    ]
