# Generated by Django 5.2.11 on 2026-03-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0009_alter_match_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='complete',
            field=models.BooleanField(default=False, verbose_name="'Complete'"),
        ),
        migrations.AlterField(
            model_name='match',
            name='submitted',
            field=models.BooleanField(default=False, verbose_name='GSheet'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='ch_name',
            field=models.CharField(default='</Null>', max_length=128, verbose_name='Clone Hero Name'),
        ),
    ]
