# Generated by Django 6.0.1 on 2026-02-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0009_remove_tournamentround_ended_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='tiebraker',
            new_name='tiebreaker',
        ),
    ]
