# Generated by Django 3.2.6 on 2026-01-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0009_auto_20260129_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='quali',
            field=models.CharField(default='59636d4c-fd3f-11f0-a815-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Qualifier ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='id',
            field=models.CharField(default='59633502-fd3f-11f0-a815-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='id',
            field=models.CharField(default='59633502-fd3f-11f0-a815-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
    ]
