# Generated by Django 5.2.11 on 2026-03-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0010_alter_match_complete_alter_match_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualifier',
            name='output',
            field=models.BooleanField(default=True, verbose_name='Discord msg on submissiom'),
        ),
    ]
