# Generated by Django 6.0.1 on 2026-02-03 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0010_rename_tiebraker_chart_tiebreaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentbracket',
            name='last_win_picks',
            field=models.BooleanField(default=True, verbose_name='Loser Last Round Picks'),
        ),
        migrations.AddField(
            model_name='tournamentbracket',
            name='tiebeaker_csc',
            field=models.BooleanField(default=False, verbose_name='Tibeaker CSC Rules'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_matches', to='corpoch.bracketgroup', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_matches', to='corpoch.bracketgroup', verbose_name='Group'),
        ),
    ]
