# Generated by Django 3.2.6 on 2026-01-30 00:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0010_auto_20260129_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bracketgroup',
            options={'verbose_name': 'Bracket Groups', 'verbose_name_plural': 'Bracket Groups'},
        ),
        migrations.AlterModelOptions(
            name='qualifiersubmission',
            options={'verbose_name': 'Qualifier Submission', 'verbose_name_plural': 'Qualifier Submissions'},
        ),
        migrations.RenameField(
            model_name='tournamentbracket',
            old_name='bans',
            new_name='num_bans',
        ),
        migrations.AddField(
            model_name='tournamentbracket',
            name='num_players',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)], verbose_name='Players'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='url',
            field=models.URLField(blank=True, default=1, verbose_name='Chart URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='quali',
            field=models.CharField(default='efe6367a-fd74-11f0-9cb4-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Qualifier ID'),
        ),
        migrations.AlterField(
            model_name='tournamentbracket',
            name='allow_defer',
            field=models.BooleanField(default=True, verbose_name='Allow Ban Deferral'),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='proof_channel',
            field=models.BigIntegerField(blank=True, default=-1, verbose_name='Discord Proof Channel ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='ref_role',
            field=models.BigIntegerField(blank=True, default=-1, verbose_name='Discord Ref Role ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='id',
            field=models.CharField(default='efe5ff34-fd74-11f0-9cb4-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='id',
            field=models.CharField(default='efe5ff34-fd74-11f0-9cb4-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='config',
            field=models.JSONField(default=dict, verbose_name='Player Configuration'),
        ),
    ]
