# Generated by Django 6.0.1 on 2026-02-03 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0011_tournamentbracket_last_win_picks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField()),
                ('chart', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='corpoch.chart', verbose_name='Chart Banned')),
                ('completed_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_completeds_rounds', to='corpoch.tournamentmatchcompleted', verbose_name='Completed Match ID')),
                ('ongoing_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_ongoing_rounds', to='corpoch.tournamentmatchongoing', verbose_name='Ongoing Match ID')),
                ('player', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_bans', to='corpoch.groupseed', verbose_name='Player')),
            ],
            options={
                'verbose_name': 'Match Ban',
                'verbose_name_plural': 'Match Bans',
                'ordering': ['num'],
            },
        ),
    ]
