# Generated by Django 3.2.6 on 2026-01-30 02:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0012_auto_20260130_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentbracket',
            name='num_rounds',
            field=models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(25)], verbose_name='Best Of'),
        ),
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='quali',
            field=models.CharField(default='d4ad8e24-fd80-11f0-9bae-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Qualifier ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='id',
            field=models.CharField(default='d4ad5c2e-fd80-11f0-9bae-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='id',
            field=models.CharField(default='d4ad5c2e-fd80-11f0-9bae-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
    ]
