# Generated by Django 6.0.1 on 2026-02-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0012_matchban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='match_players',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_players', to='corpoch.groupseed', verbose_name='Players'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='match_players',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_players', to='corpoch.groupseed', verbose_name='Players'),
        ),
    ]
