# Generated by Django 6.0.3 on 2026-03-26 02:42

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('corpoch', '0012_create_discorduser'),
        ('dbot', '0002_guilds_channels_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbot.roles', verbose_name='Bracket Role'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='score_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbot.channels', verbose_name='Score Log Channel'),
        ),
        migrations.AlterField(
            model_name='group',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbot.roles', verbose_name='Group Role'),
        ),
        migrations.AlterField(
            model_name='match',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbot.channels', verbose_name='Ref-Tool Discord Channel'),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbot.channels', verbose_name='Submission Discord Channel'),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='output',
            field=models.BooleanField(default=True, verbose_name='Msg On Submissiom'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='guild',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbot.guilds', verbose_name='Discord Guild'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbot.roles', verbose_name='Participant Role'),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='proof_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbot.channels', verbose_name='Discord Proof Channel'),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='ref_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbot.roles', verbose_name='Discord Ref Role'),
        ),
    ]
