# Generated by Django 6.0.1 on 2026-02-03 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0013_alter_tournamentmatchcompleted_match_players_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmatchcompleted',
            name='bans',
        ),
        migrations.RemoveField(
            model_name='tournamentmatchongoing',
            name='bans',
        ),
        migrations.AlterField(
            model_name='matchban',
            name='completed_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_bans', to='corpoch.tournamentmatchcompleted', verbose_name='Completed Match ID'),
        ),
        migrations.AlterField(
            model_name='matchban',
            name='ongoing_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_bans', to='corpoch.tournamentmatchongoing', verbose_name='Ongoing Match ID'),
        ),
    ]
