# Generated by Django 6.0.3 on 2026-03-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0013_alter_bracket_role_alter_bracket_score_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='flags',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='global_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='locale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='public_flags',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
