# Generated by Django 3.2.6 on 2026-01-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0013_auto_20260130_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='quali',
            field=models.CharField(default='d7b607f4-fd80-11f0-8a6c-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Qualifier ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='id',
            field=models.CharField(default='d7b5d306-fd80-11f0-8a6c-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='id',
            field=models.CharField(default='d7b5d306-fd80-11f0-8a6c-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
    ]
