# Generated by Django 6.0.3 on 2026-03-27 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0014_alter_discorduser_avatar_alter_discorduser_flags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentplayer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
