# Generated by Django 5.2.11 on 2026-02-04 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0014_remove_tournamentmatchcompleted_bans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupseed',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_seeding', to='corpoch.tournamentplayer', verbose_name='Group Seed'),
        ),
    ]
