# Generated by Django 3.2.6 on 2026-01-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0014_auto_20260130_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='blake3',
            field=models.CharField(default='NONE', max_length=32, verbose_name='blake3 hash'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='md5',
            field=models.CharField(default='NONE', max_length=32, verbose_name='md5 hash'),
        ),
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='quali',
            field=models.CharField(default='a910b920-fd8b-11f0-8b1f-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Qualifier ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='id',
            field=models.CharField(default='a91086d0-fd8b-11f0-8b1f-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='id',
            field=models.CharField(default='a91086d0-fd8b-11f0-8b1f-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
    ]
