# Generated by Django 6.0.3 on 2026-03-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0015_alter_tournamentplayer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifier',
            name='output',
            field=models.BooleanField(default=True, verbose_name='Msg On Submission'),
        ),
    ]
