# Generated by Django 6.0.3 on 2026-03-29 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0015_alter_tournamentplayer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifier',
            name='output',
            field=models.BooleanField(default=True, verbose_name='Msg On Submission'),
        ),
        migrations.AlterField(
            model_name='match',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.RemoveField(
            model_name='discorduser',
            name='username',
        ),
    ]
