# Generated by Django 5.2.11 on 2026-02-04 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0015_alter_groupseed_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentbracket',
            old_name='last_win_picks',
            new_name='last_loser_picks',
        ),
    ]
