# Generated by Django 3.2.6 on 2026-01-30 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0016_auto_20260130_0327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bracketgroup',
            options={'verbose_name': 'Bracket Group', 'verbose_name_plural': 'Bracket Groups'},
        ),
        migrations.AlterModelOptions(
            name='chart',
            options={'verbose_name': 'Chart', 'verbose_name_plural': 'Charts'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'Tournament', 'verbose_name_plural': 'Tournaments'},
        ),
        migrations.AlterModelOptions(
            name='tournamentbracket',
            options={'verbose_name': 'Tournament Bracket', 'verbose_name_plural': 'Tournament Brackets'},
        ),
        migrations.AlterModelOptions(
            name='tournamentplayer',
            options={'verbose_name': 'Tournament Player', 'verbose_name_plural': 'Tournament Players'},
        ),
        migrations.AlterModelOptions(
            name='tournamentqualifier',
            options={'verbose_name': 'Qualifier', 'verbose_name_plural': 'Qualifiers'},
        ),
        migrations.RemoveField(
            model_name='tournamentmatchcompleted',
            name='match_results',
        ),
        migrations.RemoveField(
            model_name='tournamentmatchongoing',
            name='match_results',
        ),
        migrations.AlterField(
            model_name='chart',
            name='album',
            field=models.CharField(blank=True, max_length=256, verbose_name='Album'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='artist',
            field=models.CharField(blank=True, max_length=256, verbose_name='Artist'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='blake3',
            field=models.CharField(blank=True, max_length=32, verbose_name='Blake3 Hash'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='charter',
            field=models.CharField(blank=True, max_length=32, verbose_name='Charter'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='md5',
            field=models.CharField(blank=True, max_length=32, verbose_name='MD5 Hash'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Chart Name'),
        ),
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='quali',
            field=models.CharField(default='194335ae-fdf7-11f0-9a9f-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Qualifier ID'),
        ),
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='steg_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='Steg Data'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='id',
            field=models.CharField(default='1942e766-fdf7-11f0-9a9f-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='id',
            field=models.CharField(default='1942e766-fdf7-11f0-9a9f-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('started_on', models.DateTimeField(auto_now_add=True, verbose_name='Started')),
                ('ended_on', models.DateTimeField(blank=True, verbose_name='Ended')),
                ('steg_data', models.JSONField(blank=True, verbose_name='Steg Data')),
                ('screenshot', models.ImageField(upload_to='tournament_screens/', verbose_name='Screenshot')),
                ('chart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corpoch.chart', verbose_name='Chart Played')),
                ('completed_match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corpoch.tournamentmatchcompleted', verbose_name='Completed Match')),
                ('ongoing_match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corpoch.tournamentmatchongoing', verbose_name='Ongoing Match')),
                ('picked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked', to='corpoch.tournamentplayer', verbose_name='Player That Picked')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='corpoch.tournamentplayer', verbose_name='Winner')),
            ],
            options={
                'verbose_name': 'Tournament Match Round',
                'verbose_name_plural': 'Tournament Match Rounds',
            },
        ),
    ]
