# Generated by Django 6.0.3 on 2026-04-01 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0016_alter_qualifier_output'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bracketrules',
            options={'verbose_name': 'Bracket Rules', 'verbose_name_plural': 'Bracket Rules'},
        ),
    ]
