# Generated by Django 6.0.3 on 2026-04-01 19:47

import django
from django.db import migrations
import django_pydantic_field
import django.core.serializers.json
import corpoch.types


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0016_alter_qualifier_output'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bracketrules',
            options={'verbose_name': 'Bracket Rules', 'verbose_name_plural': 'Bracket Rules'},
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='config',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=corpoch.types.PlayerConfig, verbose_name='Player Configuration'),
        ),
    ]
