# Generated by Django 6.0.3 on 2026-03-31 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0017_alter_bracketrules_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentplayer',
            name='ch_name',
        ),
    ]
