# Generated by Django 3.2.6 on 2026-01-31 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0018_auto_20260130_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentmatchongoing',
            options={'verbose_name': 'Ongoing Tournament Match', 'verbose_name_plural': 'Ongoing Tournament Matches'},
        ),
        migrations.AlterModelOptions(
            name='tournamentround',
            options={'verbose_name': 'Group Match Round', 'verbose_name_plural': 'Group Match Rounds'},
        ),
        migrations.AddField(
            model_name='tournamentmatchcompleted',
            name='loser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matches_lost', to='corpoch.tournamentplayer', verbose_name='Loser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournamentmatchcompleted',
            name='winner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matches_won', to='corpoch.tournamentplayer', verbose_name='Winner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournamentround',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_rounds', to='corpoch.bracketgroup', verbose_name='Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='quali',
            field=models.CharField(default='522463ae-fe59-11f0-9276-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Qualifier ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='id',
            field=models.CharField(default='5223ff72-fe59-11f0-9276-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='id',
            field=models.CharField(default='5223ff72-fe59-11f0-9276-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='chart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds_played', to='corpoch.chart', verbose_name='Chart Played'),
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='completed_match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_match_rounds', to='corpoch.tournamentmatchcompleted', verbose_name='Completed Match'),
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='ongoing_match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ongoing_match_rounds', to='corpoch.tournamentmatchongoing', verbose_name='Ongoing Match'),
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='picked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='corpoch.tournamentplayer', verbose_name='Player That Picked'),
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds_won', to='corpoch.tournamentplayer', verbose_name='Winner'),
        ),
    ]
