# Generated by Django 6.0.3 on 2026-04-05 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0018_remove_tournamentplayer_ch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentplayer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Server Discord Name'),
        ),
    ]
