# Generated by Django 3.2.6 on 2026-01-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0019_auto_20260131_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='quali',
            field=models.CharField(default='6c2bc256-fe59-11f0-839b-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Qualifier ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='id',
            field=models.CharField(default='6c2b6298-fe59-11f0-839b-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='id',
            field=models.CharField(default='6c2b6298-fe59-11f0-839b-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
    ]
