# Generated by Django 6.0.3 on 2026-04-09 17:06

import corpoch.models
import corpoch.types
import corpoch.validators
import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_pydantic_field.fields
import multiselectfield.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models

def update_player_fk(apps, schema_editor):
        MatchBan = apps.get_model('corpoch', 'MatchBan')
        GroupSeed = apps.get_model('corpoch', 'GroupSeed')
        TournamentPlayer = apps.get_model('corpoch', 'TournamentPlayer')

        for ban in MatchBan.objects.all():
                ban.player_fk = ban.player.player
                ban.save()

class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0019_alter_tournamentplayer_user'),
        ('dbot', '0002_guilds_channels_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchban',
            name='player_fk',
            field=models.ForeignKey(blank=True, help_text='Player that chose a ban.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tempfk', to='corpoch.tournamentplayer', verbose_name='Temp new Player FK'),
        ),
	    migrations.RunPython(update_player_fk),
        migrations.RemoveField(
            model_name='matchban',
            name='player',
        ),
        migrations.RenameField(
            model_name='matchban',
            old_name='player_fk',
            new_name='player',
        ),
        migrations.AlterField(
            model_name='bracket',
            name='id',
            field=models.AutoField(help_text='Internal ID of a bracket.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Is bracket active/matches are allowed to start.', verbose_name='Bracket Active'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='name',
            field=models.CharField(default='New Bracket', help_text='Name of the bracket', max_length=128, verbose_name='Bracket Name'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='revealed',
            field=models.BooleanField(default=False, help_text='Is the setlist revealed. If True, the charts for a setlist are made available.', verbose_name='Setlist Revealed'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Discord role to assign to players in this bracket.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbot.roles', verbose_name='Bracket Role'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='tournament',
            field=models.ForeignKey(help_text='Tournament this bracket is for.', on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='corpoch.tournament', verbose_name='Tournament'),
        ),
        migrations.AlterField(
            model_name='bracketrules',
            name='ban_ruleset',
            field=models.CharField(choices=[('default', 'No Defer/High Seed first'), ('deferban', 'High Seed can defer ban/picks first'), ('deferboth', 'High Seed can defers both ban/pick')], default='default', help_text='Ruleset to determine how bans work.', max_length=32, verbose_name='Match Bans Ruleset'),
        ),
        migrations.AlterField(
            model_name='bracketrules',
            name='bracket',
            field=models.OneToOneField(help_text='Bracket this ruleset is for.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ruleset', serialize=False, to='corpoch.bracket', verbose_name='Bracket Rules'),
        ),
        migrations.AlterField(
            model_name='bracketrules',
            name='num_bans',
            field=models.IntegerField(default=1, help_text='Number of bans per-player in a match.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Bans Per-Player'),
        ),
        migrations.AlterField(
            model_name='bracketrules',
            name='num_players',
            field=models.PositiveIntegerField(default=2, help_text='Number of players in a match.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)], verbose_name='Players'),
        ),
        migrations.AlterField(
            model_name='bracketrules',
            name='num_rounds',
            field=models.PositiveIntegerField(default=7, help_text='Maximum number of rounds per-match.', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(25)], verbose_name='Best Of'),
        ),
        migrations.AlterField(
            model_name='bracketrules',
            name='pick_ruleset',
            field=models.CharField(choices=[('loserpicks', 'High Seed 1st Pick/Loser Picks'), ('alternate', 'Alternate player picks')], default='loserpicks', help_text='Ruleset to determine who picks the next song for a round.', max_length=32, verbose_name="'Who Picks' Ruleset"),
        ),
        migrations.AlterField(
            model_name='bracketrules',
            name='tb_ruleset',
            field=models.CharField(choices=[('single', 'Single TB'), ('csc', 'CSC TB Rules'), ('banpick', "'NPDO' Ban/Pick"), ('refdecide', 'Ref picks from unplayed')], default='single', help_text='Ruleset to determine how tiebreakers player.', max_length=32, verbose_name='Tiebreaker Ruleset'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='album',
            field=models.CharField(blank=True, help_text='Album the song is from.', max_length=256, verbose_name='Album'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='artist',
            field=models.CharField(blank=True, help_text='Artist of the song.', max_length=256, verbose_name='Artist'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='blake3',
            field=models.CharField(blank=True, help_text='The Encore blake3 hash for a chart to import.', max_length=32, verbose_name='Blake3 Hash'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='brackets',
            field=models.ManyToManyField(blank=True, help_text='Bracket setlists this chart is used in.', related_name='setlist', to='corpoch.bracket', verbose_name='Bracket Setlist'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='charter',
            field=models.CharField(blank=True, help_text='Author of a chart.', max_length=32, verbose_name='Charter'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='difficulty',
            field=models.CharField(choices=[('expert', 'Expert'), ('hard', 'Hard'), ('medium', 'Medium'), ('easy', 'Easy')], default='expert', help_text='Difficulty this chart is to be played on.', max_length=16, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='icon',
            field=models.ForeignKey(blank=True, help_text='The in-game setlist icon for the chart.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charts', to='corpoch.chicon', verbose_name='CH Icon'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='id',
            field=models.AutoField(help_text='Internal ID of a chart.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chart',
            name='md5',
            field=models.CharField(blank=True, help_text='The md5sum of the notes.chart/mid file. Used for steg verification.', max_length=32, verbose_name='MD5 Hash'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='modifiers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NM', 'No Modifiers'), ('AH', 'All Hopos'), ('AS', 'All Strums'), ('AT', 'All Taps'), ('AO', 'All Opens'), ('BM', 'Brutal Mode'), ('DD', 'Deadly Dynamics'), ('DN', 'Double Notes'), ('DS', 'Dropless Sustains'), ('PM', 'Precision Mode'), ('NS', 'Note Shuffle'), ('DK', 'Double Kick'), ('NK', 'No Kick')], default='NM', help_text='Modifiers expected to be used.', max_length=38, verbose_name='Modifiers'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the chart.', max_length=256, verbose_name='Chart Name'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='sngfile',
            field=models.FileField(blank=True, help_text='The chart file. Stored as .sng but available as old .chart format.', null=True, upload_to='sngfiles/', validators=[corpoch.validators.validate_chart_file], verbose_name='SNG File'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='speed',
            field=models.PositiveIntegerField(default=100, help_text='Expected playback speed.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1000)], verbose_name='Speed'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='tiebreaker',
            field=models.BooleanField(default=False, help_text='Is this chart a tiebreaker in a setlist.', verbose_name='Tiebreaker'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='url',
            field=models.URLField(blank=True, help_text='URL this chart is available at.', verbose_name='Chart URL'),
        ),
        migrations.AlterField(
            model_name='chicon',
            name='img',
            field=models.ImageField(blank=True, help_text='URL of the chart icon.', null=True, upload_to='chicons/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='chicon',
            name='name',
            field=models.CharField(default='newicon', help_text='The icon name.', max_length=32, primary_key=True, serialize=False, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='avatar',
            field=models.CharField(blank=True, help_text='URL of users discord avatar.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='global_name',
            field=models.CharField(blank=True, help_text='Global or display name used on the account.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='id',
            field=models.BigIntegerField(help_text='Discord snowflake ID of user.', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='last_login',
            field=models.DateTimeField(blank=True, help_text="User's last login time.", null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='locale',
            field=models.CharField(blank=True, help_text="Users's Discord locale", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='mfa_enabled',
            field=models.BooleanField(default=False, help_text='Does user have MFA enabled for their Discord account.'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='public_flags',
            field=models.IntegerField(blank=True, help_text="Discord account badge/flag's.", null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='bracket',
            field=models.ForeignKey(help_text='Bracket this Group belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='corpoch.bracket', verbose_name='Bracket'),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.AutoField(db_index=True, help_text='The ID of the Group', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='A', help_text='Group Name, full name constructed from tournament.short_name + bracket.name + group.name', max_length=8, verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Discord role from Tournament Guild to be assigned to group members', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbot.roles', verbose_name='Group Role'),
        ),
        migrations.AlterField(
            model_name='groupseed',
            name='group',
            field=models.ForeignKey(help_text='Group this seed is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seeding', to='corpoch.group', verbose_name='Group Seeding'),
        ),
        migrations.AlterField(
            model_name='groupseed',
            name='id',
            field=models.AutoField(help_text='Internal ID for this seed', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupseed',
            name='player',
            field=models.ForeignKey(help_text='Player with this seeding in the group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_seeding', to='corpoch.tournamentplayer', verbose_name='Group Seed'),
        ),
        migrations.AlterField(
            model_name='groupseed',
            name='seed',
            field=models.PositiveIntegerField(help_text='Player seed within this group'),
        ),
        migrations.AlterField(
            model_name='match',
            name='channel',
            field=models.ForeignKey(blank=True, help_text='Discord Channel the reftool was ran in for a match.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbot.channels', verbose_name='Ref-Tool Discord Channel'),
        ),
        migrations.AlterField(
            model_name='match',
            name='complete',
            field=models.BooleanField(default=False, help_text='Match is finalized, but waiting for screenshots.', verbose_name="'Complete'"),
        ),
        migrations.AlterField(
            model_name='match',
            name='defer',
            field=models.BooleanField(default=False, help_text='Was a deferral used.', verbose_name='Deferral Used'),
        ),
        migrations.AlterField(
            model_name='match',
            name='ended_on',
            field=models.DateTimeField(blank=True, help_text='Match end time.', null=True, verbose_name='Match End Time'),
        ),
        migrations.AlterField(
            model_name='match',
            name='exhibition',
            field=models.BooleanField(default=False, help_text='Is a match an exhibition match (not an official match).'),
        ),
        migrations.AlterField(
            model_name='match',
            name='finished',
            field=models.BooleanField(default=False, help_text='Match is finished and has all screenshots/data.', verbose_name='Finished'),
        ),
        migrations.AlterField(
            model_name='match',
            name='group',
            field=models.ForeignKey(help_text='Group the match was played for.', on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='corpoch.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.CharField(default=uuid.uuid1, help_text='UUID for a match.', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(blank=True, help_text='Player that lost the match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_lost', to='corpoch.tournamentplayer'),
        ),
        migrations.AlterField(
            model_name='match',
            name='message',
            field=models.BigIntegerField(blank=True, help_text='Discord snowflake ID of the message for a match.', null=True, verbose_name='Ref-Tool Discord Message ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(blank=True, help_text='Players that participated in a match.', related_name='match_players', to='corpoch.groupseed', verbose_name='Players'),
        ),
        migrations.AlterField(
            model_name='match',
            name='referee',
            field=models.ForeignKey(blank=True, help_text='Discord User for the refree of a match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_reffed', to=settings.AUTH_USER_MODEL, verbose_name='Referee'),
        ),
        migrations.AlterField(
            model_name='match',
            name='started_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Match start time.', verbose_name='Match Start Time'),
        ),
        migrations.AlterField(
            model_name='match',
            name='submitted',
            field=models.BooleanField(default=False, help_text='Match is uploaded to GSheet for Tournament.', verbose_name='GSheet'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, help_text='Player that won the match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='corpoch.tournamentplayer'),
        ),
        migrations.AlterField(
            model_name='matchban',
            name='chart',
            field=models.ForeignKey(blank=True, help_text='The chart that was banned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans', to='corpoch.chart', verbose_name='Chart Banned'),
        ),
        migrations.AlterField(
            model_name='matchban',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp a ban was chosen.', null=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='matchban',
            name='id',
            field=models.AutoField(help_text='Internal ID for a ban.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchban',
            name='match',
            field=models.ForeignKey(blank=True, help_text='Match a ban was made for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_bans', to='corpoch.match', verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='matchban',
            name='num',
            field=models.PositiveIntegerField(help_text='Order in which a ban was picked.'),
        ),
        migrations.AlterField(
            model_name='matchban',
            name='player',
            field=models.ForeignKey(blank=True, help_text='Player that chose a ban.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_bans', to='corpoch.groupseed', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='chart',
            field=models.ForeignKey(blank=True, help_text='Chart that was played.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds_played', to='corpoch.chart', verbose_name='Chart Played'),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp the round was started.', null=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='id',
            field=models.AutoField(help_text='Internal ID for a round.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='loser',
            field=models.ForeignKey(blank=True, help_text='Loser of a round.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds_lost', to='corpoch.tournamentplayer', verbose_name='Loser'),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='match',
            field=models.ForeignKey(blank=True, help_text='Match the round was played for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_rounds', to='corpoch.match', verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='num',
            field=models.PositiveIntegerField(help_text='Round number of a specific match.'),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='picked',
            field=models.ForeignKey(blank=True, help_text='Player that picked the chart played.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='corpoch.tournamentplayer', verbose_name='Picker'),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Screenshot for a match.', null=True, upload_to=corpoch.models.steg_upload_dir, verbose_name='Screenshot'),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='steg',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Clone Hero screenshot steg data.', null=True, schema=corpoch.types.StegScreenshot, verbose_name='Steg Data'),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='winner',
            field=models.ForeignKey(blank=True, help_text='Winner of a round.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds_won', to='corpoch.tournamentplayer', verbose_name='Winner'),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='bracket',
            field=models.ForeignKey(blank=True, help_text='Specific bracket in a tournament this qualifier is for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualifier', to='corpoch.bracket', verbose_name='Bracket'),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='channel',
            field=models.ForeignKey(blank=True, help_text='Discord Channel users will submit scores in.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbot.channels', verbose_name='Submission Discord Channel'),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='charts',
            field=models.ManyToManyField(help_text='Chart(s) that this qualifier uses.', related_name='charts', to='corpoch.chart', verbose_name='Qualifier Chart(s)'),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='UTC Time this qualifier ends. +2 hours from this time, the results are allowed in the API.', verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='form_link',
            field=models.URLField(blank=True, help_text='Google Form link to show players while submitting their qualifier.', null=True, verbose_name='Google Form Link'),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='gsheet',
            field=models.URLField(blank=True, help_text='Google Sheet to submit qualifier scores to.', null=True, verbose_name='Submissions Google Sheet'),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='id',
            field=models.AutoField(help_text='Internal ID of this Qualifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='limit_submissions',
            field=models.BooleanField(default=False, help_text='Limit players to single qualifier submission.', verbose_name='Limit Submissions to # Required'),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='output',
            field=models.BooleanField(default=True, help_text='Publically post in discord when user submits a qualifier.', verbose_name='Msg On Submission'),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='required_submissions',
            field=models.PositiveIntegerField(default=1, help_text='If limit_submissions=False, the number of submissions required for a player to qualify.', verbose_name='Required Submissions'),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='rules',
            field=models.TextField(default='Placeholder rules', help_text='Rules shown to players for this qualifier.', max_length=1024, verbose_name='Rules'),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='tournament',
            field=models.ForeignKey(help_text='Tournament this qualifer is for.', on_delete=django.db.models.deletion.CASCADE, related_name='qualifier', to='corpoch.tournament', verbose_name='Tournament'),
        ),
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='id',
            field=models.CharField(default=uuid.uuid1, help_text='UUID of the submission.', max_length=40, primary_key=True, serialize=False, verbose_name='Qualifier ID'),
        ),
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='player',
            field=models.ForeignKey(help_text='The Player that submitted a qualifier.', on_delete=django.db.models.deletion.CASCADE, related_name='qualifiers', to='corpoch.tournamentplayer', verbose_name='Submittor'),
        ),
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='qualifier',
            field=models.ForeignKey(help_text='Qualifier that a submission was sent for.', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='corpoch.qualifier', verbose_name='Tournament Qualifier'),
        ),
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='The screenshot for a submission.', null=True, upload_to=corpoch.models.quali_upload_dir, verbose_name='Screenshot'),
        ),
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='steg',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Clone Hero screenshot steg data.', null=True, schema=corpoch.types.StegScreenshot, verbose_name='Steg Data'),
        ),
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Submission timestamp.', verbose_name='Submission Time'),
        ),
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='submitted',
            field=models.BooleanField(default=False, help_text='Is submission sent to associated GSheet.', verbose_name='Uploaded to GSheet'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='active',
            field=models.BooleanField(default=False, help_text='Is tournament active/running.', verbose_name='In-Progress'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='guild',
            field=models.ForeignKey(help_text='Discord Guild the tournament is running in.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbot.guilds', verbose_name='Discord Guild'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='id',
            field=models.AutoField(help_text='Internal ID of a tournament.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='New Tournament', help_text='Full name of the tournament.', max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Discord Role to assign to players in this tournament.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbot.roles', verbose_name='Participant Role'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='short_name',
            field=models.CharField(default='NT1', help_text='Short/abbreviated name for this tournament.', max_length=16, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='enable_gsheets',
            field=models.BooleanField(default=True, help_text='Are GSheets in use for this tournament', verbose_name='GSheets Integration'),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='gsheet',
            field=models.URLField(blank=True, help_text='GSheet URL to post match results to.', null=True, verbose_name='Match Reporting Google Sheet'),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='id',
            field=models.AutoField(help_text='Internal ID of a config.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='ref_role',
            field=models.ForeignKey(blank=True, help_text="Discord Role for referee's to start matches.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbot.roles', verbose_name='Discord Ref Role'),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='rules',
            field=models.TextField(default='Some rules go here', help_text='Rules shown to players.', max_length=1024, verbose_name='Rules'),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='tournament',
            field=models.OneToOneField(help_text='Tournament a configuration is for.', on_delete=django.db.models.deletion.CASCADE, related_name='config', to='corpoch.tournament', verbose_name='Tournament Configuration'),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='version',
            field=models.CharField(choices=[('v1.0.0.4080-final', 'v1.0.0.4080-final')], default='v1.0.0.4080-final', help_text='Clone Hero verison the tournament is using.', max_length=32, verbose_name='Clone Hero Version'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='config',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='JSON Configuration feild for player', schema=corpoch.types.PlayerConfig, verbose_name='Player Configuration'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='id',
            field=models.AutoField(help_text='Internal ID of the Player', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Is player active. False means DNF/Did not enter.', verbose_name='Player Active'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='name',
            field=models.CharField(blank=True, help_text='Display name of user in Tournament Guild', max_length=128, null=True, verbose_name='Guild Discord Name'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='tournament',
            field=models.ForeignKey(help_text='Tournament player signed up for.', on_delete=django.db.models.deletion.CASCADE, related_name='players', to='corpoch.tournament', verbose_name='Tournament'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Discord User for Player', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
