# Generated by Django 6.0.3 on 2026-04-09 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0020_matchban_player_fk_alter_bracket_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchban',
            name='player',
            field=models.ForeignKey(blank=True, help_text='Player that chose a ban.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_bans', to='corpoch.tournamentplayer', verbose_name='Player'),
        ),
    ]
