# Generated by Django 3.2.6 on 2026-01-31 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0020_auto_20260131_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatchcompleted',
            name='player1_ban',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournamentmatchcompleted_player1_ban', to='corpoch.chart', verbose_name='Player 1 Ban'),
        ),
        migrations.AddField(
            model_name='tournamentmatchcompleted',
            name='player2_ban',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournamentmatchcompleted_player2_ban', to='corpoch.chart', verbose_name='Player 2 Ban'),
        ),
        migrations.AddField(
            model_name='tournamentmatchongoing',
            name='player1_ban',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournamentmatchongoing_player1_ban', to='corpoch.chart', verbose_name='Player 1 Ban'),
        ),
        migrations.AddField(
            model_name='tournamentmatchongoing',
            name='player2_ban',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournamentmatchongoing_player2_ban', to='corpoch.chart', verbose_name='Player 2 Ban'),
        ),
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='quali',
            field=models.CharField(default='8738f106-fe5c-11f0-ae15-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Qualifier ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='id',
            field=models.CharField(default='87388fcc-fe5c-11f0-ae15-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='id',
            field=models.CharField(default='87388fcc-fe5c-11f0-ae15-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
    ]
