# Generated by Django 3.2.6 on 2026-01-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0021_auto_20260131_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifiersubmission',
            name='quali',
            field=models.CharField(default='88b90b74-fe5c-11f0-b406-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Qualifier ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchcompleted',
            name='id',
            field=models.CharField(default='88b8b408-fe5c-11f0-b406-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchongoing',
            name='id',
            field=models.CharField(default='88b8b408-fe5c-11f0-b406-0050569d2030', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
    ]
