# Generated by Django 6.0.3 on 2026-04-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0021_alter_matchban_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentconfig',
            name='enable_gsheets',
        ),
        migrations.AddField(
            model_name='bracketrules',
            name='boss_active',
            field=models.BooleanField(default=False, help_text="Are 'Boss' songs allowed to be picked.", verbose_name='Boss Songs Active'),
        ),
        migrations.AddField(
            model_name='bracketrules',
            name='boss_bannable',
            field=models.BooleanField(default=False, help_text="Are 'Boss' songs bannable.", verbose_name='Boss Songs Bannable'),
        ),
        migrations.AddField(
            model_name='chart',
            name='boss',
            field=models.BooleanField(default=False, help_text="Is chart a 'boss' song.", verbose_name='Boss Song'),
        ),
        migrations.AddField(
            model_name='groupseed',
            name='eliminated',
            field=models.BooleanField(default=False, help_text='Has player been eliminted from bracket (playoffs).', verbose_name='Eliminated'),
        ),
    ]
