# Generated by Django 6.0.3 on 2026-05-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0022_alter_tournamentconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentconfig',
            name='version',
            field=models.CharField(choices=[('v1.0.0.4080-final', 'v1.0.0.4080-final'), ('v1.1.0.6085-final', 'v1.1.0.6085-final')], default='v1.0.0.4080-final', help_text='Clone Hero verison the tournament is using.', max_length=32, verbose_name='Clone Hero Version'),
        ),
    ]
