# Generated by Django 6.0.3 on 2026-05-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0023_alter_tournamentconfig_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='instrument',
            field=models.CharField(choices=[('guitar', 'Guitar'), ('coop', 'Guitar Coop'), ('bass', 'Bass'), ('rhythm', 'Rhythm'), ('keys', 'Keys'), ('drums', 'Drums'), ('ghl', 'GHL Guitar'), ('ghlbass', 'GHL Bass'), ('ghlrythm', 'GHL Rhythm'), ('ghlkeys', 'GHL Keys'), ('ghlcoop', 'GHL Guitar Coop')], default='guitar', max_length=32, verbose_name='Instrument'),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='charts',
            field=models.ManyToManyField(help_text='Chart(s) that this qualifier uses.', related_name='qualifier', to='corpoch.chart', verbose_name='Qualifier Chart(s)'),
        ),
    ]
