# Generated by Django 6.0.3 on 2026-05-04 21:06

import django.utils.timezone
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0024_alter_chart_instrument_alter_qualifier_charts'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordtoken',
            name='expires',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Token expiry time.', verbose_name='Expiry Time'),
        ),
        migrations.AddField(
            model_name='discordtoken',
            name='scopes',
            field=encrypted_fields.fields.EncryptedTextField(default='identify guilds', max_length=64),
        ),
        migrations.AlterField(
            model_name='discordtoken',
            name='id',
            field=models.AutoField(help_text='Internal ID of a token.', primary_key=True, serialize=False),
        ),
    ]
