# Generated by Django 6.0.3 on 2026-05-09 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0025_discordtoken_expires_discordtoken_scopes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gsheetapi',
            name='sa_name',
        ),
    ]
