# Generated by Django 5.2.11 on 2026-02-12 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0025_rename_qualifier_chart_tournamentqualifier_chart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TournamentRound',
            new_name='MatchRound',
        ),
        migrations.RenameModel(
            old_name='TournamentQualifier',
            new_name='Qualifier',
        ),
        migrations.RenameField(
            model_name='matchround',
            old_name='steg_data',
            new_name='steg',
        ),
        migrations.RenameField(
            model_name='qualifiersubmission',
            old_name='quali',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='qualifiersubmission',
            old_name='steg_json',
            new_name='steg',
        ),
    ]
