# Generated by Django 6.0.6 on 2026-06-23 22:29

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0026_remove_gsheetapi_sa_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='modifiers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NM', 'No Modifiers'), ('AH', 'All Hopos'), ('AS', 'All Strums'), ('AT', 'All Taps'), ('AO', 'All Opens'), ('BM', 'Brutal Mode'), ('DD', 'Deadly Dynamics'), ('DK', 'Double Kick'), ('DN', 'Double Notes'), ('DS', 'Dropless Sustains'), ('NK', 'No Kick'), ('NS', 'Note Shuffle'), ('PM', 'Precision Mode')], default='NM', help_text='Modifiers expected to be used.', max_length=38, verbose_name='Modifiers'),
        ),
    ]
