# Generated by Django 5.2.11 on 2026-02-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0026_rename_tournamentround_matchround_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsheetapi',
            name='sa_name',
            field=models.CharField(default='corpo-dev-bot@corpo-dev-dev-sheets-app.iam.gserviceaccount.com', max_length=96, verbose_name='API Service Account Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualifiersubmission',
            name='submitted',
            field=models.BooleanField(default=False, verbose_name='Uploaded to GSheet'),
        ),
        migrations.AddField(
            model_name='tournamentconfig',
            name='gsheet',
            field=models.URLField(blank=True, null=True, verbose_name='Match Reporting Google Sheet'),
        ),
        migrations.AddField(
            model_name='tournamentmatchcompleted',
            name='submitted',
            field=models.BooleanField(default=False, verbose_name='Uploaded to GSheet'),
        ),
    ]
