# Generated by Django 6.0.7 on 2026-08-05 23:42

import corpoch.models.match
import corpoch.types
import corpoch.validators
import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import django_pydantic_field.fields
import multiselectfield.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('corpoch', '0026_remove_gsheetapi_sa_name'),
        ('dbot', '0005_chemoji_name_alter_chemoji_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartAbstract',
            fields=[
                ('id', models.AutoField(help_text='Internal ID of a chart.', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Name of the chart.', max_length=256, verbose_name='Chart Name')),
                ('artist', models.CharField(blank=True, help_text='Artist of the song.', max_length=256, verbose_name='Artist')),
                ('album', models.CharField(blank=True, help_text='Album the song is from.', max_length=256, verbose_name='Album')),
                ('charter', models.CharField(blank=True, help_text='Author of a chart.', max_length=32, verbose_name='Charter')),
                ('difficulty', models.CharField(choices=[('expert', 'Expert'), ('hard', 'Hard'), ('medium', 'Medium'), ('easy', 'Easy')], default='expert', help_text='Difficulty this chart is to be played on.', max_length=16, verbose_name='Difficulty')),
                ('instrument', models.CharField(choices=[('guitar', 'Guitar'), ('coop', 'Guitar Coop'), ('bass', 'Bass'), ('rhythm', 'Rhythm'), ('keys', 'Keys'), ('drums', 'Drums'), ('ghl', 'GHL Guitar'), ('ghlbass', 'GHL Bass'), ('ghlrythm', 'GHL Rhythm'), ('ghlkeys', 'GHL Keys'), ('ghlcoop', 'GHL Guitar Coop')], default='guitar', max_length=32, verbose_name='Instrument')),
                ('modifiers', multiselectfield.db.fields.MultiSelectField(choices=[('NM', 'No Modifiers'), ('AH', 'All Hopos'), ('AS', 'All Strums'), ('AT', 'All Taps'), ('AO', 'All Opens'), ('BM', 'Brutal Mode'), ('DD', 'Deadly Dynamics'), ('DK', 'Double Kick'), ('DN', 'Double Notes'), ('DS', 'Dropless Sustains'), ('NK', 'No Kick'), ('NS', 'Note Shuffle'), ('PM', 'Precision Mode')], default='NM', help_text='Modifiers expected to be used.', max_length=38, verbose_name='Modifiers')),
                ('speed', models.PositiveIntegerField(default=100, help_text='Expected playback speed.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1000)], verbose_name='Speed')),
                ('md5', models.CharField(blank=True, help_text='The md5sum of the notes.chart/mid file. Used for steg verification.', max_length=32, verbose_name='MD5 Hash')),
                ('blake3', models.CharField(blank=True, help_text='The Encore blake3 hash for a chart to import.', max_length=32, verbose_name='Blake3 Hash')),
                ('url', models.URLField(blank=True, help_text='URL this chart is available at.', verbose_name='Chart URL')),
                ('sngfile', models.FileField(blank=True, help_text='The chart file. Stored as .sng but available as old .chart format.', null=True, upload_to='sngfiles/', validators=[corpoch.validators.validate_chart_file], verbose_name='SNG File')),
                ('icon', models.ForeignKey(blank=True, help_text='The in-game setlist icon for the chart.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charts', to='corpoch.chicon', verbose_name='CH Icon')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='MatchAbstract',
            fields=[
                ('id', models.CharField(default=uuid.uuid1, help_text='UUID for a match.', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID')),
                ('defer', models.BooleanField(default=False, help_text='Was a deferral used.', verbose_name='Deferral Used')),
                ('started_on', models.DateTimeField(auto_now_add=True, help_text='Match start time.', verbose_name='Match Start Time')),
                ('ended_on', models.DateTimeField(blank=True, help_text='Match end time.', null=True, verbose_name='Match End Time')),
                ('complete', models.BooleanField(default=False, help_text='Match is finalized, but waiting for screenshots.', verbose_name="'Complete'")),
                ('finished', models.BooleanField(default=False, help_text='Match is finished and has all screenshots/data.', verbose_name='Finished')),
                ('submitted', models.BooleanField(default=False, help_text='Match is uploaded to GSheet for Tournament.', verbose_name='GSheet')),
                ('message', models.BigIntegerField(blank=True, help_text='Discord snowflake ID of the message for a match.', null=True, verbose_name='Ref-Tool Discord Message ID')),
                ('exhibition', models.BooleanField(default=False, help_text='Is a match an exhibition match (not an official match).')),
                ('channel', models.ForeignKey(blank=True, help_text='Discord Channel the reftool was ran in for a match.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbot.channels', verbose_name='Ref-Tool Discord Channel')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='MatchBanAbstract',
            fields=[
                ('id', models.AutoField(help_text='Internal ID for a ban.', primary_key=True, serialize=False)),
                ('num', models.PositiveIntegerField(help_text='Order in which a ban was picked.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp a ban was chosen.', null=True, verbose_name='Created Time')),
                ('chart', models.ForeignKey(blank=True, help_text='Chart that was played.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='corpoch.chartabstract', verbose_name='Chart Played')),
                ('match', models.ForeignKey(blank=True, help_text='Match the round was played for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_bans', to='corpoch.matchabstract', verbose_name='Match ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='MatchRoundAbstract',
            fields=[
                ('id', models.AutoField(help_text='Internal ID for a round.', primary_key=True, serialize=False)),
                ('num', models.PositiveIntegerField(help_text='Round number of a specific match.')),
                ('steg', django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Clone Hero screenshot steg data.', null=True, schema=corpoch.types.StegScreenshot, verbose_name='Steg Data')),
                ('screenshot', models.ImageField(blank=True, help_text='Screenshot for a match.', null=True, upload_to=corpoch.models.match.steg_upload_dir, verbose_name='Screenshot')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp the round was started.', null=True, verbose_name='Created Time')),
                ('chart', models.ForeignKey(blank=True, help_text='Chart that was played.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='corpoch.chartabstract', verbose_name='Chart Played')),
                ('match', models.ForeignKey(blank=True, help_text='Match the round was played for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_rounds', to='corpoch.matchabstract', verbose_name='Match ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
        ),
        migrations.AlterModelOptions(
            name='discordtoken',
            options={'verbose_name': 'Discord Token', 'verbose_name_plural': 'Discord Tokens'},
        ),
        migrations.AlterModelOptions(
            name='discorduser',
            options={'verbose_name': 'Discord User', 'verbose_name_plural': 'Discord Users'},
        ),
        migrations.RemoveField(
            model_name='chart',
            name='album',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='blake3',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='charter',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='id',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='md5',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='modifiers',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='sngfile',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='url',
        ),
        migrations.RemoveField(
            model_name='match',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='match',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='match',
            name='defer',
        ),
        migrations.RemoveField(
            model_name='match',
            name='ended_on',
        ),
        migrations.RemoveField(
            model_name='match',
            name='exhibition',
        ),
        migrations.RemoveField(
            model_name='match',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='match',
            name='id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='message',
        ),
        migrations.RemoveField(
            model_name='match',
            name='started_on',
        ),
        migrations.RemoveField(
            model_name='match',
            name='submitted',
        ),
        migrations.RemoveField(
            model_name='matchban',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='matchban',
            name='created',
        ),
        migrations.RemoveField(
            model_name='matchban',
            name='id',
        ),
        migrations.RemoveField(
            model_name='matchban',
            name='match',
        ),
        migrations.RemoveField(
            model_name='matchban',
            name='num',
        ),
        migrations.RemoveField(
            model_name='matchround',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='matchround',
            name='created',
        ),
        migrations.RemoveField(
            model_name='matchround',
            name='id',
        ),
        migrations.RemoveField(
            model_name='matchround',
            name='match',
        ),
        migrations.RemoveField(
            model_name='matchround',
            name='num',
        ),
        migrations.RemoveField(
            model_name='matchround',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='matchround',
            name='steg',
        ),
        migrations.AddField(
            model_name='bracketrules',
            name='byos_group_only',
            field=models.BooleanField(default=True, help_text='Limit BYOS charts to only those in same group instead of bracket.', verbose_name='Pick from Group BYOS Only'),
        ),
        migrations.AddField(
            model_name='bracketrules',
            name='byos_picks',
            field=models.IntegerField(default=1, help_text='Number of BYOS chart picks a player gets per-match.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='BYOS Picks per match'),
        ),
        migrations.AddField(
            model_name='tournamentconfig',
            name='byos',
            field=models.BooleanField(default=False, help_text='Are BYOS charts being used', verbose_name='Bring Your Own Song Rules'),
        ),
        migrations.AddField(
            model_name='chart',
            name='chartabstract_ptr',
            field=models.OneToOneField(auto_created=True, default=17, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='corpoch.chartabstract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='matchabstract_ptr',
            field=models.OneToOneField(auto_created=True, default=33, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='corpoch.matchabstract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchban',
            name='matchbanabstract_ptr',
            field=models.OneToOneField(auto_created=True, default=26, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='corpoch.matchbanabstract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchround',
            name='matchroundabstract_ptr',
            field=models.OneToOneField(auto_created=True, default=29, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='corpoch.matchroundabstract'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BYOSChart',
            fields=[
                ('chartabstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='corpoch.chartabstract')),
                ('group', models.ManyToManyField(blank=True, help_text='Groups using this chart in their BYOS Pool', related_name='byos_setlist', to='corpoch.group', verbose_name='Groups')),
            ],
            options={
                'verbose_name': 'BYOS Chart',
                'verbose_name_plural': 'BYOS Charts',
            },
            bases=('corpoch.chartabstract',),
        ),
        migrations.CreateModel(
            name='ExhibitionMatch',
            fields=[
                ('matchabstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='corpoch.matchabstract')),
                ('bracket', models.ForeignKey(help_text='Bracket the exhibition match was played for.', on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_matches', to='corpoch.bracket', verbose_name='Bracket')),
                ('loser', models.ForeignKey(blank=True, help_text='Player that lost the exhibition match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibitions_lost', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, help_text='Players that participated in an exhibition match.', related_name='exhibition_players', to=settings.AUTH_USER_MODEL, verbose_name='Players')),
                ('referee', models.ForeignKey(blank=True, help_text='Discord User for the refree of a match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibition_matches_reffed', to=settings.AUTH_USER_MODEL, verbose_name='Referee')),
                ('tournament', models.ForeignKey(help_text='Tournament', on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_matches', to='corpoch.tournament', verbose_name='Tournament')),
                ('winner', models.ForeignKey(blank=True, help_text='Player that won the exhibition match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibitions_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exhibition Match',
                'verbose_name_plural': 'Exhibition Matches',
                'ordering': ['-started_on'],
            },
            bases=('corpoch.matchabstract',),
        ),
        migrations.CreateModel(
            name='ExhibitionMatchBan',
            fields=[
                ('matchbanabstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='corpoch.matchbanabstract')),
                ('player', models.ForeignKey(blank=True, help_text='Player that chose a ban.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibition_bans', to=settings.AUTH_USER_MODEL, verbose_name='Player')),
            ],
            options={
                'verbose_name': 'Exhibition Match Ban',
                'verbose_name_plural': 'Exhibition Match Bans',
                'ordering': ['num'],
                'get_latest_by': 'num',
            },
            bases=('corpoch.matchbanabstract',),
        ),
        migrations.CreateModel(
            name='ExhibitionMatchRound',
            fields=[
                ('matchroundabstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='corpoch.matchroundabstract')),
                ('loser', models.ForeignKey(blank=True, help_text='Loser of a round.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibition_rounds_lost', to=settings.AUTH_USER_MODEL, verbose_name='Loser')),
                ('picked', models.ForeignKey(blank=True, help_text='Player that picked the chart played.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_picks', to=settings.AUTH_USER_MODEL, verbose_name='Picker')),
                ('winner', models.ForeignKey(blank=True, help_text='Winner of a round.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibition_rounds_won', to=settings.AUTH_USER_MODEL, verbose_name='Winner')),
            ],
            options={
                'verbose_name': 'Exhibition Match Round',
                'verbose_name_plural': 'Exhibition Match Rounds',
                'ordering': ['num'],
                'get_latest_by': 'num',
            },
            bases=('corpoch.matchroundabstract',),
        ),
    ]
