# Generated by Django 6.0.8 on 2026-08-31 01:41

import corpoch.models.match
import corpoch.types
import django.core.serializers.json
import django.db.models.deletion
import django_pydantic_field.fields
import uuid
from django.conf import settings
from django.db import migrations, models

def forwards_func(apps, schema_editor):
    chart = apps.get_model('corpoch', 'Chart')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    new_ct = ContentType.objects.get_for_model(chart)
    chart.objects.filter(polymorphic_ctype__isnull=True).update(polymorphic_ctype=new_ct)

class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('corpoch', '0027_alter_chart_modifiers'),
        ('dbot', '0005_chemoji_name_alter_chemoji_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discordtoken',
            options={'verbose_name': 'Discord Token', 'verbose_name_plural': 'Discord Tokens'},
        ),
        migrations.AlterModelOptions(
            name='discorduser',
            options={'verbose_name': 'Discord User', 'verbose_name_plural': 'Discord Users'},
        ),
        migrations.AddField(
            model_name='chart',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython),
        migrations.AddField(
            model_name='tournamentconfig',
            name='byos',
            field=models.BooleanField(default=False, help_text='Are BYOS charts being used', verbose_name='Bring Your Own Song Rules'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='charter',
            field=models.CharField(blank=True, help_text='Author of a chart.', max_length=64, verbose_name='Charter'),
        ),
        migrations.AlterField(
            model_name='matchban',
            name='chart',
            field=models.ForeignKey(blank=True, help_text='Chart that was banned.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='corpoch.chart', verbose_name='Chart Banned'),
        ),
        migrations.AlterField(
            model_name='matchban',
            name='match',
            field=models.ForeignKey(blank=True, help_text='Match the round was played for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_bans', to='corpoch.match', verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='chart',
            field=models.ForeignKey(blank=True, help_text='Chart that was played.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='corpoch.chart', verbose_name='Chart Played'),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='version',
            field=models.CharField(choices=[('v1.0.0.4080-final', 'v1.0.0.4080-final'), ('v1.1.0.6085-final', 'v1.1.0.6142-final')], default='v1.0.0.4080-final', help_text='Clone Hero verison the tournament is using.', max_length=32, verbose_name='Clone Hero Version'),
        ),
        migrations.CreateModel(
            name='BYOSChart',
            fields=[
                ('chart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='corpoch.chart')),
                ('groups', models.ManyToManyField(blank=True, help_text='Groups using this chart in their BYOS Pool', related_name='byos_setlist', to='corpoch.group', verbose_name='Groups')),
            ],
            options={
                'verbose_name': 'BYOS Chart',
                'verbose_name_plural': 'BYOS Charts',
            },
            bases=('corpoch.chart',),
        ),
        migrations.CreateModel(
            name='ExhibitionMatch',
            fields=[
                ('id', models.CharField(default=uuid.uuid1, help_text='UUID for a match.', max_length=40, primary_key=True, serialize=False, verbose_name='Match ID')),
                ('defer', models.BooleanField(default=False, help_text='Was a deferral used.', verbose_name='Deferral Used')),
                ('started_on', models.DateTimeField(auto_now_add=True, help_text='Match start time.', verbose_name='Match Start Time')),
                ('ended_on', models.DateTimeField(blank=True, help_text='Match end time.', null=True, verbose_name='Match End Time')),
                ('complete', models.BooleanField(default=False, help_text='Match is finalized, but waiting for screenshots.', verbose_name="'Complete'")),
                ('finished', models.BooleanField(default=False, help_text='Match is finished and has all screenshots/data.', verbose_name='Finished')),
                ('submitted', models.BooleanField(default=False, help_text='Match is uploaded to GSheet for Tournament.', verbose_name='GSheet')),
                ('message', models.BigIntegerField(blank=True, help_text='Discord snowflake ID of the message for a match.', null=True, verbose_name='Ref-Tool Discord Message ID')),
                ('exhibition', models.BooleanField(default=False, help_text='Is a match an exhibition match (not an official match).')),
                ('bracket', models.ForeignKey(help_text='Bracket the exhibition match was played for.', on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_matches', to='corpoch.bracket', verbose_name='Bracket')),
                ('channel', models.ForeignKey(blank=True, help_text='Discord Channel the reftool was ran in for a match.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbot.channels', verbose_name='Ref-Tool Discord Channel')),
                ('loser', models.ForeignKey(blank=True, help_text='Player that lost the exhibition match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibitions_lost', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, help_text='Players that participated in an exhibition match.', related_name='exhibition_players', to=settings.AUTH_USER_MODEL, verbose_name='Players')),
                ('referee', models.ForeignKey(blank=True, help_text='Discord User for the refree of a match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibition_matches_reffed', to=settings.AUTH_USER_MODEL, verbose_name='Referee')),
                ('tournament', models.ForeignKey(help_text='Tournament', on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_matches', to='corpoch.tournament', verbose_name='Tournament')),
                ('winner', models.ForeignKey(blank=True, help_text='Player that won the exhibition match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibitions_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exhibition Match',
                'verbose_name_plural': 'Exhibition Matches',
                'ordering': ['-started_on'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitionMatchBan',
            fields=[
                ('id', models.AutoField(help_text='Internal ID for a ban.', primary_key=True, serialize=False)),
                ('num', models.PositiveIntegerField(help_text='Order in which a ban was picked.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp a ban was chosen.', null=True, verbose_name='Created Time')),
                ('chart', models.ForeignKey(blank=True, help_text='Chart that was banned.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='corpoch.chart', verbose_name='Chart Banned')),
                ('match', models.ForeignKey(blank=True, help_text='Match the round was played for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_bans', to='corpoch.exhibitionmatch', verbose_name='Match ID')),
                ('player', models.ForeignKey(blank=True, help_text='Player that chose a ban.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibition_bans', to=settings.AUTH_USER_MODEL, verbose_name='Player')),
            ],
            options={
                'verbose_name': 'Exhibition Match Ban',
                'verbose_name_plural': 'Exhibition Match Bans',
                'ordering': ['num'],
                'get_latest_by': 'num',
            },
        ),
        migrations.CreateModel(
            name='ExhibitionMatchRound',
            fields=[
                ('id', models.AutoField(help_text='Internal ID for a round.', primary_key=True, serialize=False)),
                ('num', models.PositiveIntegerField(help_text='Round number of a specific match.')),
                ('screenshot', models.ImageField(blank=True, help_text='Screenshot for a match.', null=True, upload_to=corpoch.models.match.steg_upload_dir, verbose_name='Screenshot')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp the round was started.', null=True, verbose_name='Created Time')),
                ('steg', django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Clone Hero screenshot steg data.', null=True, schema=corpoch.types.StegScreenshot, verbose_name='Steg Data')),
                ('chart', models.ForeignKey(blank=True, help_text='Chart that was played.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='corpoch.chart', verbose_name='Chart Played')),
                ('loser', models.ForeignKey(blank=True, help_text='Loser of a round.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibition_rounds_lost', to=settings.AUTH_USER_MODEL, verbose_name='Loser')),
                ('match', models.ForeignKey(blank=True, help_text='Match the round was played for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_rounds', to='corpoch.exhibitionmatch', verbose_name='Match ID')),
                ('picked', models.ForeignKey(blank=True, help_text='Player that picked the chart played.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_picks', to=settings.AUTH_USER_MODEL, verbose_name='Picker')),
                ('winner', models.ForeignKey(blank=True, help_text='Winner of a round.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibition_rounds_won', to=settings.AUTH_USER_MODEL, verbose_name='Winner')),
            ],
            options={
                'verbose_name': 'Exhibition Match Round',
                'verbose_name_plural': 'Exhibition Match Rounds',
                'ordering': ['num'],
                'get_latest_by': 'num',
            },
        ),
        migrations.AddField(
            model_name='bracketrules',
            name='byos_group_only',
            field=models.BooleanField(default=True, help_text='Limit BYOS charts to only those in same group instead of bracket.', verbose_name='Pick from Group BYOS Only'),
        ),
        migrations.AddField(
            model_name='bracketrules',
            name='byos_picks',
            field=models.IntegerField(default=1, help_text='Number of BYOS chart picks a player gets per-match.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='BYOS Picks per match'),
        ),
    ]
