# Generated by Django 5.2.11 on 2026-02-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0027_gsheetapi_sa_name_qualifiersubmission_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Discord Name'),
        ),
    ]
