# Generated by Django 6.0.3 on 2026-08-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoch', '0027_alter_chart_modifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='charter',
            field=models.CharField(blank=True, help_text='Author of a chart.', max_length=64, verbose_name='Charter'),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='version',
            field=models.CharField(choices=[('v1.0.0.4080-final', 'v1.0.0.4080-final'), ('v1.1.0.6085-final', 'v1.1.0.6142-final')], default='v1.0.0.4080-final', help_text='Clone Hero verison the tournament is using.', max_length=32, verbose_name='Clone Hero Version'),
        ),
    ]
